// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
	"user-management/internal/biz"
	"user-management/internal/conf"
	"user-management/internal/data"
	"user-management/internal/server"
	"user-management/internal/service"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

func wireApp(confServer *conf.Server, confData *conf.Data, logger log.Logger) (*kratos.App, func(), error) {
	dataData, cleanup, err := data.NewData(confData, logger)
	if err != nil {
		return nil, nil, err
	}
	tenantsRepo := data.NewTenantsRepo(dataData, logger)
	tenantsUsecase := biz.NewTenantsUsecase(tenantsRepo, logger)
	tenantsService := service.NewTenantsService(tenantsUsecase, dataData, logger)
	grpcServer := server.NewGRPCServer(confServer, tenantsService, logger)
	httpServer := server.NewHTTPServer(confServer, tenantsService, logger)
	app := newApp(logger, grpcServer, httpServer)
	return app, func() {
		cleanup()
	}, nil
}
