export const LEGAL_EFFECTIVE_DATE = '[Add date]';
export const LEGAL_CONTACT_EMAIL = 'naveen.dey@artpark.in';

export const TERMS_SECTIONS = [
  {
    title: 'Use of the Platform',
    paragraphs: [
      'Taksa is provided for lawful and authorized use only.',
      'Users agree not to misuse the platform, interfere with its operation, attempt unauthorized access, or use the service in a way that could harm Taksa, its users, or connected systems.'
    ]
  },
  {
    title: 'Account Access',
    paragraphs: [
      'Users are responsible for maintaining the confidentiality of their login method and account access.',
      'If a user signs in through Google or another third-party provider, the user is responsible for the security of that provider account as well.'
    ]
  },
  {
    title: 'Authorized Access and Roles',
    paragraphs: [
      'Access to Taksa features may depend on account status, assigned roles, organization membership, and platform permissions.',
      'Taksa may restrict, suspend, or revoke access where necessary for operational, administrative, or security reasons.'
    ]
  },
  {
    title: 'Platform Availability',
    paragraphs: [
      'Taksa may change, update, improve, suspend, or discontinue any part of the platform at any time.',
      'Taksa does not guarantee uninterrupted or error-free availability of the service.'
    ]
  },
  {
    title: 'Open Source and Platform Usage',
    paragraphs: [
      'Taksa may include open source components, platform integrations, dashboards, APIs, and industrial data services.',
      'Use of those components may also be subject to applicable third-party or open source license terms where relevant.'
    ]
  },
  {
    title: 'Data and Security',
    paragraphs: [
      'Users must not attempt to bypass security controls, access data without authorization, or use the platform in a way that compromises integrity, confidentiality, or availability.'
    ]
  },
  {
    title: 'Limitation of Liability',
    paragraphs: [
      'To the maximum extent permitted by law, Taksa is provided on an "as is" and "as available" basis.',
      'Taksa and its operators are not liable for indirect, incidental, special, consequential, or business-interruption damages arising from use of the platform.'
    ]
  },
  {
    title: 'Changes to the Terms',
    paragraphs: [
      'Taksa may revise these Terms of Service from time to time. Continued use of the platform after changes become effective constitutes acceptance of the updated terms.'
    ]
  },
  {
    title: 'Contact',
    paragraphs: ['For questions regarding these Terms of Service, please contact:'],
    contactEmail: LEGAL_CONTACT_EMAIL
  }
];

export const PRIVACY_SECTIONS = [
  {
    title: 'Information We Collect',
    paragraphs: [
      'When a user signs in to Taksa, we may collect and store limited account information required to authenticate the user and provide access to the platform.',
      'This may include:'
    ],
    bullets: [
      'full name',
      'email address',
      'profile information provided by the selected sign-in provider',
      'account identifiers generated by our authentication system',
      'login and session-related metadata required for security and access control'
    ]
  },
  {
    title: 'Google Sign-In Data',
    paragraphs: [
      'If Google Sign-In is used, Taksa may receive basic profile information such as the user’s name, email address, and profile identity information made available through Google authentication.'
    ]
  },
  {
    title: 'How We Use Information',
    paragraphs: ['Taksa uses this information only for legitimate platform purposes, including:'],
    bullets: [
      'authenticating users',
      'creating or linking user accounts',
      'managing user sessions',
      'controlling access to dashboards, APIs, and platform resources',
      'improving platform security, reliability, and user support'
    ]
  },
  {
    title: 'What We Do Not Do',
    paragraphs: [
      'Taksa does not sell personal information obtained through authentication.',
      'Taksa does not use Google user data for advertising.',
      'Taksa does not share authentication data with third parties except where required to operate the service, comply with legal obligations, or protect the security and integrity of the platform.'
    ]
  },
  {
    title: 'Data Storage and Security',
    paragraphs: [
      'Authentication and account information may be stored securely in Taksa’s identity and access management systems for login, authorization, user management, and audit purposes.',
      'Reasonable technical and organizational safeguards are used to protect user data from unauthorized access, misuse, alteration, or disclosure.'
    ]
  },
  {
    title: 'Third-Party Authentication',
    paragraphs: [
      'Taksa may use third-party identity providers, including Google, to authenticate users.',
      'When a user chooses Google Sign-In, the authentication process is handled through Google and Taksa’s identity platform. Taksa only receives the information necessary to identify the user, create or link the account, and manage secure access.'
    ]
  },
  {
    title: 'User Rights and Choices',
    paragraphs: [
      'Users may request updates or corrections to their account information where applicable.',
      'Users may also choose not to use Google Sign-In and instead use any other authentication method that Taksa makes available.'
    ]
  },
  {
    title: 'Retention',
    paragraphs: [
      'Taksa retains user account and authentication data only as long as reasonably necessary for platform operation, security, compliance, account administration, and legitimate business purposes.'
    ]
  },
  {
    title: 'Changes to This Policy',
    paragraphs: [
      'Taksa may update this Privacy Policy from time to time. Any updates will be reflected on this page with a revised effective date.'
    ]
  },
  {
    title: 'Contact',
    paragraphs: ['For privacy-related questions, please contact:'],
    contactEmail: LEGAL_CONTACT_EMAIL
  }
];

export const LEGAL_DOCUMENTS = {
  terms: {
    eyebrow: 'AGREEMENT',
    title: 'Platform Agreement',
    effectiveDate: LEGAL_EFFECTIVE_DATE,
    intro: [
      'These Terms of Service govern access to and use of Taksa.',
      'By accessing or using Taksa, the user agrees to these terms.'
    ],
    sections: TERMS_SECTIONS
  },
  privacy: {
    eyebrow: 'PRIVACY',
    title: 'Privacy Policy',
    effectiveDate: LEGAL_EFFECTIVE_DATE,
    intro: [
      'Taksa respects the privacy of its users and is committed to handling personal information responsibly.'
    ],
    sections: PRIVACY_SECTIONS
  }
};
