'use client';

import React, { useEffect, useRef, useState } from 'react';
import { ChevronDown, Copy, Info, Maximize2, Trash2, X } from 'lucide-react';
import './Edit-readflow.css';

const defaultModbusYaml = `modbus:
  addresses:
    - address: 1025
      name: FirstFlagOfDiscreteInput
      register: holding
      type: UINT16
    - address: 1024
      name: ZeroElementOfInputRegister
      register: holding
      type: UINT16
  controller: "tcp://{{ .IP }}:{{ .PORT }}"
  slaveIDs:
    - 1
  timeBetweenReads: 1s
  timeout: 1s`;

const defaultOpcuaYaml = `opcua:
  endpoint: 'opc.tcp://{{ .IP }}:{{ .PORT }}' # OPC UA server endpoint
  nodeIDs:
    - "ns=2;s=MyVariable" # Node ID to subscribe to. Adjust as necessary
  subscribeInterval: '1s' # Interval for subscription updates`;

const getDefaultInputYaml = (protocol) => {
    if (String(protocol || '').toLowerCase() === 'opcua') {
        return defaultOpcuaYaml;
    }
    return defaultModbusYaml;
};

const injectYaml = `buffer:
  none: {}`;

const defaultAlwaysCode = `msg.meta.location_path = "{{ .location_path }}";
msg.meta.data_contract = "_historian";
msg.meta.tag_name = msg.meta.modbus_tag_name;
msg.meta.virtual_path = "";
msg.meta.timestamp_ms = Date.now();
return msg;`;

const EditReadflow = ({ bridgeConfig, setBridgeConfig }) => {
    const [inputYaml, setInputYaml] = useState(() => bridgeConfig?.readInputYaml || getDefaultInputYaml(bridgeConfig?.protocol));
    const [injectYamlValue, setInjectYamlValue] = useState(bridgeConfig?.readRawYamlInject || injectYaml);
    const [isEditingInputYaml, setIsEditingInputYaml] = useState(false);
    const [isEditingInjectYaml, setIsEditingInjectYaml] = useState(false);
    const [fullscreenEditor, setFullscreenEditor] = useState({ open: false, type: 'input', conditionId: null });
    const [pendingDeleteConditionId, setPendingDeleteConditionId] = useState(null);
    const [processingView, setProcessingView] = useState('Visual');
    const [expandedAlways, setExpandedAlways] = useState(false);
    const [expandedConditions, setExpandedConditions] = useState({});
    const [conditions, setConditions] = useState([
        { id: 1, condition: 'msg.meta.modbus_tag_name === "FirstFlagOfDiscreteInput"', action: 'msg.payload = Number(msg.payload) > 0 ? 1 : 0;\nmsg.meta.unit = "raw";\nmsg.meta.modbus_tag_datatype = "uint64";\nmsg.meta.modbus_tag_datatype_json = "number";\nreturn msg;' },
        { id: 2, condition: 'msg.meta.modbus_tag_name === "ZeroElementOfInputRegister"', action: 'msg.payload = Number(msg.payload);\nmsg.meta.unit = "raw";\nmsg.meta.modbus_tag_datatype = "uint64";\nmsg.meta.modbus_tag_datatype_json = "number";\nreturn msg;' }
    ]);
    const [defaultsCode, setDefaultsCode] = useState(defaultAlwaysCode);
    const [advancedProcessingCode, setAdvancedProcessingCode] = useState('return msg;');
    const [processingCodeYaml, setProcessingCodeYaml] = useState('');
    const inputYamlRef = useRef(null);
    const injectYamlRef = useRef(null);
    const defaultsCodeRef = useRef(null);
    const processingCodeRef = useRef(null);
    const lastAutoGeneratedYamlRef = useRef('');
    const didMountRef = useRef(false);
    const didProcessorInitRef = useRef(false);
    const didLoadProcessorFromBridgeRef = useRef(false);
    const [isEditingDefaultsCode, setIsEditingDefaultsCode] = useState(false);
    const [isEditingConditionActions, setIsEditingConditionActions] = useState({});
    const [isEditingProcessingCode, setIsEditingProcessingCode] = useState(false);

    const toTagProcessorYaml = (processingYaml) => {
        const normalized = String(processingYaml || '').trim();

        if (!normalized) {
            return 'tag_processor:\n  advancedProcessing: |-\n    return msg;';
        }

        if (normalized.startsWith('tag_processor:')) {
            return normalized;
        }

        const indented = normalized
            .split('\n')
            .map((line) => `  ${line}`)
            .join('\n');

        return `tag_processor:\n${indented}`;
    };

    const toggleCondition = (id) => {
        setExpandedConditions((prev) => ({
            ...prev,
            [id]: !prev[id]
        }));
    };

    const addCondition = () => {
        const newId = Math.max(...conditions.map((c) => c.id), 0) + 1;
        setConditions((prev) => [
            ...prev,
            { id: newId, condition: 'Enter condition...', action: 'return msg;' }
        ]);
    };

    const openFullscreenEditor = (type, conditionId = null) => {
        setFullscreenEditor({ open: true, type, conditionId });
    };

    const closeFullscreenEditor = () => {
        if (fullscreenEditor.type === 'processing-code') {
            handleProcessingCodeBlur(processingCodeYaml);
        }
        setFullscreenEditor((prev) => ({ ...prev, open: false }));
    };

    const requestDeleteCondition = (id) => {
        setPendingDeleteConditionId(id);
    };

    const confirmDeleteCondition = () => {
        if (pendingDeleteConditionId === null) {
            return;
        }

        const id = pendingDeleteConditionId;
        setConditions((prev) => prev.filter((c) => c.id !== id));
        setExpandedConditions((prev) => {
            const newExpanded = { ...prev };
            delete newExpanded[id];
            return newExpanded;
        });

        setPendingDeleteConditionId(null);
    };

    const getModalEditorValue = () => {
        if (fullscreenEditor.type === 'inject') {
            return injectYamlValue;
        }

        if (fullscreenEditor.type === 'defaults') {
            return defaultsCode;
        }

        if (fullscreenEditor.type === 'condition-action') {
            const activeCondition = conditions.find((condition) => condition.id === fullscreenEditor.conditionId);
            return activeCondition?.action || '';
        }

        if (fullscreenEditor.type === 'processing-code') {
            return processingCodeYaml;
        }

        return inputYaml;
    };

    const setModalEditorValue = (value) => {
        if (fullscreenEditor.type === 'inject') {
            setInjectYamlValue(value);
            return;
        }

        if (fullscreenEditor.type === 'defaults') {
            setDefaultsCode(value);
            return;
        }

        if (fullscreenEditor.type === 'condition-action') {
            updateCondition(fullscreenEditor.conditionId, 'action', value);
            return;
        }

        if (fullscreenEditor.type === 'processing-code') {
            setProcessingCodeYaml(value);
            return;
        }

        setInputYaml(value);
    };

    const getModalEditorTitle = () => {
        if (fullscreenEditor.type === 'inject') {
            return 'YAML Inject (Advanced)';
        }

        if (fullscreenEditor.type === 'defaults') {
            return 'Always';
        }

        if (fullscreenEditor.type === 'condition-action') {
            const index = conditions.findIndex((condition) => condition.id === fullscreenEditor.conditionId);
            return `Condition ${index + 1} - Then Action`;
        }

        if (fullscreenEditor.type === 'processing-code') {
            return 'Processing (Tag Processor) - Code';
        }

        return 'Input (YAML)';
    };

    const getLineNumbers = (value) => {
        const lineCount = Math.max(String(value || '').split('\n').length, 1);
        return Array.from({ length: lineCount }, (_, index) => index + 1).join('\n');
    };

    const updateCondition = (id, field, value) => {
        setConditions((prev) =>
            prev.map((c) => (c.id === id ? { ...c, [field]: value } : c))
        );
    };

    const copyCondition = async (conditionText) => {
        if (!navigator?.clipboard) {
            return;
        }

        try {
            await navigator.clipboard.writeText(conditionText);
        } catch {
            // no-op
        }
    };

    const parseProcessingCodeView = (yaml) => {
        const text = String(yaml || '').replace(/\r\n/g, '\n');

        const stripIndent = (block, spaces) => {
            const prefix = ' '.repeat(spaces);
            return String(block || '')
                .split('\n')
                .map((line) => (line.startsWith(prefix) ? line.slice(spaces) : line))
                .join('\n')
                .replace(/\s+$/, '');
        };

        const advancedMatch = text.match(/(?:^|\n)advancedProcessing:\s*\|-?\n([\s\S]*?)(?=\nconditions:|\n$)/);
        const conditionsMatch = text.match(/(?:^|\n)conditions:\s*\n([\s\S]*?)(?=\ndefaults:|\n$)/);
        const defaultsMatch = text.match(/(?:^|\n)defaults:\s*\|\n([\s\S]*?)$/);

        if (!defaultsMatch && !conditionsMatch && !advancedMatch) {
            return null;
        }

        const parsedDefaults = defaultsMatch ? stripIndent(defaultsMatch[1], 2) : null;
        const parsedAdvanced = advancedMatch ? stripIndent(advancedMatch[1], 2) : null;

        let parsedConditions = null;
        if (conditionsMatch) {
            const condBlock = conditionsMatch[1];
            const entries = condBlock.split(/\n(?=  - if:)/);
            let nextId = 1;
            parsedConditions = entries
                .map((entry) => {
                    const ifMatch = entry.match(/  - if: (.*?)(?:\n|$)/);
                    const thenMatch = entry.match(/    then:\s*\|\n([\s\S]*?)(?=\n  - if:|$)/);
                    if (!ifMatch) {
                        return null;
                    }
                    const id = nextId;
                    nextId += 1;
                    return {
                        id,
                        condition: ifMatch[1].trim(),
                        action: thenMatch ? stripIndent(thenMatch[1], 6) : 'return msg;'
                    };
                })
                .filter(Boolean);
        }

        return { defaultsCode: parsedDefaults, conditions: parsedConditions, advancedProcessingCode: parsedAdvanced };
    };

    const stripTagProcessorRoot = (yaml) => {
        const text = String(yaml || '').replace(/\r\n/g, '\n').trim();

        if (!text.startsWith('tag_processor:')) {
            return text;
        }

        return text
            .split('\n')
            .slice(1)
            .map((line) => (line.startsWith('  ') ? line.slice(2) : line))
            .join('\n')
            .trim();
    };

    const renderProcessingCodeView = () => {
        const conditionsYaml = conditions
            .map((cond) => `  - if: ${cond.condition}\n    then: |\n${cond.action.split('\n').map((line) => `      ${line}`).join('\n')}`)
            .join('\n');

        return `advancedProcessing: |-
  ${advancedProcessingCode.split('\n').map((line) => line).join('\n  ')}
conditions:
${conditionsYaml}
defaults: |
${defaultsCode.split('\n').map((line) => `  ${line}`).join('\n')}`;
    };

    useEffect(() => {
        const next = renderProcessingCodeView();
        lastAutoGeneratedYamlRef.current = next;
        setProcessingCodeYaml(next);
    }, [defaultsCode, conditions, advancedProcessingCode]);

    const handleProcessingCodeBlur = (value) => {
        setIsEditingProcessingCode(false);

        if (!value || value === lastAutoGeneratedYamlRef.current) {
            return;
        }

        const parsed = parseProcessingCodeView(value);
        if (!parsed) {
            return;
        }

        if (parsed.defaultsCode !== null && parsed.defaultsCode !== defaultsCode) {
            setDefaultsCode(parsed.defaultsCode);
        }

        if (parsed.conditions !== null) {
            const currentSig = JSON.stringify(conditions.map((c) => ({ condition: c.condition, action: c.action })));
            const parsedSig = JSON.stringify(parsed.conditions.map((c) => ({ condition: c.condition, action: c.action })));
            if (currentSig !== parsedSig) {
                setConditions(parsed.conditions);
            }
        }

        if (parsed.advancedProcessingCode !== null && parsed.advancedProcessingCode !== advancedProcessingCode) {
            setAdvancedProcessingCode(parsed.advancedProcessingCode);
        }
    };

    useEffect(() => {
        if (didLoadProcessorFromBridgeRef.current) {
            return;
        }

        const loadedProcessorYaml = String(bridgeConfig?.readProcessorYaml || '').trim();
        if (!loadedProcessorYaml) {
            return;
        }

        const normalizedProcessorYaml = stripTagProcessorRoot(loadedProcessorYaml);
        const parsed = parseProcessingCodeView(normalizedProcessorYaml);

        if (parsed?.defaultsCode !== null) {
            setDefaultsCode(parsed.defaultsCode);
        }

        if (parsed?.conditions !== null) {
            setConditions(parsed.conditions);
        }

        if (parsed?.advancedProcessingCode !== null) {
            setAdvancedProcessingCode(parsed.advancedProcessingCode);
        }

        didLoadProcessorFromBridgeRef.current = true;
        didProcessorInitRef.current = true;
    }, [bridgeConfig?.readProcessorYaml]);

    useEffect(() => {
        if (!didMountRef.current) {
            didMountRef.current = true;
            return;
        }
        setBridgeConfig((prev) => ({
            ...prev,
            readInputYaml: inputYaml,
            readRawYamlInject: injectYamlValue,
            readInputType: String(bridgeConfig?.protocol || 'modbus').toLowerCase()
        }));
    }, [inputYaml, injectYamlValue]);

    useEffect(() => {
        if (!didProcessorInitRef.current) {
            if (processingCodeYaml !== '') {
                didProcessorInitRef.current = true;
            }
            return;
        }
        setBridgeConfig((prev) => ({
            ...prev,
            readProcessorType: 'tag_processor',
            readProcessorYaml: toTagProcessorYaml(processingCodeYaml)
        }));
    }, [processingCodeYaml]);

    const handleConfigChange = (field, value) => {
        setBridgeConfig((prev) => ({
            ...prev,
            [field]: value
        }));
    };

    useEffect(() => {
        const newDefault = getDefaultInputYaml(bridgeConfig?.protocol);
        setInputYaml((prev) => {
            if (prev === defaultModbusYaml || prev === defaultOpcuaYaml) {
                return newDefault;
            }
            return prev;
        });
    }, [bridgeConfig?.protocol]);

    useEffect(() => {
        if (isEditingInputYaml) {
            inputYamlRef.current?.focus();
        }
    }, [isEditingInputYaml]);

    useEffect(() => {
        if (isEditingInjectYaml) {
            injectYamlRef.current?.focus();
        }
    }, [isEditingInjectYaml]);

    useEffect(() => {
        if (isEditingDefaultsCode) {
            defaultsCodeRef.current?.focus();
        }
    }, [isEditingDefaultsCode]);

    useEffect(() => {
        if (isEditingProcessingCode) {
            processingCodeRef.current?.focus();
        }
    }, [isEditingProcessingCode]);

    const handleYamlKeyDown = (event, value, setValue) => {
        if (event.key !== 'Tab') {
            return;
        }

        event.preventDefault();

        const textarea = event.target;
        const start = textarea.selectionStart;
        const end = textarea.selectionEnd;
        const indentation = '  ';

        const updatedValue = `${value.slice(0, start)}${indentation}${value.slice(end)}`;
        setValue(updatedValue);

        requestAnimationFrame(() => {
            textarea.selectionStart = start + indentation.length;
            textarea.selectionEnd = start + indentation.length;
        });
    };

    return (
        <div className="bridge-readflow-container">
            <div className="bridge-readflow-config-card">
                <div className="bridge-readflow-card-header">
                    <h2>Configuration</h2>
                    <p>How to communicate with your data source</p>
                </div>

                <div className="bridge-readflow-form">
                    <div className="bridge-readflow-form-row">
                        <label>
                            Protocol
                            <span>*</span>
                        </label>

                        <div className="bridge-readflow-select-wrapper">
                            <select
                                value={bridgeConfig.protocol}
                                disabled
                            >
                                <option value="Modbus">Modbus</option>
                                <option value="OPCUA">OPCUA</option>
                            </select>
                        </div>
                    </div>

                    <div className="bridge-readflow-form-row">
                        <label>
                            Data Type
                            <span>*</span>
                        </label>

                        <div className="bridge-readflow-select-row">
                            <div className="bridge-readflow-select-wrapper">
                                <select
                                    value={bridgeConfig.dataType}
                                    disabled
                                >
                                    <option value="Time Series">Time Series</option>
                                    <option value="Custom Advanced">Custom Advanced</option>
                                </select>

                                <ChevronDown size={18} className="bridge-readflow-select-icon" />
                            </div>

                            <Info size={16} className="bridge-readflow-info-icon" />
                        </div>
                    </div>
                </div>
            </div>

            <div className="bridge-readflow-section-card">
                <h2>Input (YAML)</h2>
                <p>
                    Configure your input in YAML format. See the{' '}
                    <a href="https://docs.redpanda.com/redpanda-connect/components/inputs/about/" target="_blank" rel="noreferrer">
                        Benthos-UMH input documentation.
                    </a>
                </p>

                <div
                    className="bridge-code-editor"
                    onClick={() => setIsEditingInputYaml(true)}
                >
                    {!isEditingInputYaml && <span className="bridge-code-edit-label">Click to edit</span>}
                    <textarea
                        ref={inputYamlRef}
                        className="bridge-code-textarea"
                        value={inputYaml}
                        onChange={(e) => setInputYaml(e.target.value)}
                        onFocus={() => setIsEditingInputYaml(true)}
                        onBlur={() => setIsEditingInputYaml(false)}
                        onKeyDown={(e) => handleYamlKeyDown(e, inputYaml, setInputYaml)}
                        spellCheck={false}
                    />
                    <button
                        type="button"
                        className="bridge-code-expand-btn"
                        onClick={(event) => {
                            event.stopPropagation();
                            openFullscreenEditor('input');
                        }}
                    >
                        <Maximize2 size={18} />
                    </button>
                </div>
            </div>

            <div className="bridge-readflow-section-card">
                <div className="bridge-processing-header">
                    <div className="bridge-processing-title">
                        <h2>Processing (Tag Processor)</h2>
                        <p>
                            Transform time-series data using the tag processor. Best for industrial equipment data with tag names, timestamps, and values.{' '}
                            <a href="https://docs.redpanda.com/redpanda-connect/components/processors/tag_processor/" target="_blank" rel="noreferrer">
                                View tag processor documentation
                            </a>
                        </p>
                    </div>
                    <div className="bridge-processing-toggle">
                        <button
                            className={`toggle-btn ${processingView === 'Visual' ? 'active' : ''}`}
                            onClick={() => setProcessingView('Visual')}
                        >
                            Visual
                        </button>
                        <button
                            className={`toggle-btn ${processingView === 'Code' ? 'active' : ''}`}
                            onClick={() => setProcessingView('Code')}
                        >
                            Code
                        </button>
                    </div>
                </div>

                {processingView === 'Visual' ? (
                    <div className="bridge-processing-visual-shell">
                        <div className="bridge-processing-section">
                            <button
                                className="bridge-processing-section-header"
                                type="button"
                                onClick={() => setExpandedAlways(!expandedAlways)}
                            >
                                <span>Always</span>
                                <ChevronDown
                                    size={18}
                                    className={`chevron ${expandedAlways ? 'open' : ''}`}
                                />
                            </button>
                            {expandedAlways && (
                                <div className="bridge-processing-section-content">
                                    <div
                                        className="bridge-code-editor bridge-processing-editor"
                                        onClick={() => setIsEditingDefaultsCode(true)}
                                    >
                                        {!isEditingDefaultsCode && <span className="bridge-code-edit-label">Click to edit</span>}
                                        <textarea
                                            ref={defaultsCodeRef}
                                            className="bridge-code-textarea"
                                            value={defaultsCode}
                                            onChange={(event) => setDefaultsCode(event.target.value)}
                                            onFocus={() => setIsEditingDefaultsCode(true)}
                                            onBlur={() => setIsEditingDefaultsCode(false)}
                                            onKeyDown={(event) => handleYamlKeyDown(event, defaultsCode, setDefaultsCode)}
                                            spellCheck={false}
                                        />
                                        <button
                                            type="button"
                                            className="bridge-code-expand-btn"
                                            onClick={(event) => {
                                                event.stopPropagation();
                                                openFullscreenEditor('defaults');
                                            }}
                                        >
                                            <Maximize2 size={18} />
                                        </button>
                                    </div>
                                </div>
                            )}
                        </div>

                        <div className="bridge-processing-conditions">
                            {conditions.map((cond, index) => (
                                <div key={cond.id} className="bridge-processing-section">
                                    <div className="bridge-processing-condition-row">
                                        <div className="bridge-processing-row-actions">
                                            <button
                                                type="button"
                                                className="bridge-processing-icon-btn"
                                                onClick={() => requestDeleteCondition(cond.id)}
                                                aria-label={`Delete condition ${index + 1}`}
                                            >
                                                <Trash2 size={18} />
                                            </button>
                                            <button
                                                type="button"
                                                className="bridge-processing-icon-btn"
                                                onClick={() => copyCondition(cond.condition)}
                                                aria-label={`Copy condition ${index + 1}`}
                                            >
                                                <Copy size={18} />
                                            </button>
                                        </div>
                                        <button
                                            className="bridge-processing-section-header"
                                            type="button"
                                            onClick={() => toggleCondition(cond.id)}
                                        >
                                            <span>Condition {index + 1}</span>
                                            <span className="bridge-condition-preview">{cond.condition}</span>
                                            <ChevronDown
                                                size={18}
                                                className={`chevron ${expandedConditions[cond.id] ? 'open' : ''}`}
                                            />
                                        </button>
                                    </div>
                                    {expandedConditions[cond.id] && (
                                        <div className="bridge-processing-section-content">
                                            <div className="bridge-condition-field">
                                                <label>If Condition</label>
                                                <input
                                                    type="text"
                                                    value={cond.condition}
                                                    onChange={(e) => updateCondition(cond.id, 'condition', e.target.value)}
                                                    className="bridge-condition-input"
                                                />
                                            </div>
                                            <div className="bridge-condition-field">
                                                <label>Then Action</label>
                                                <div
                                                    className="bridge-code-editor bridge-processing-editor"
                                                    onClick={() => setIsEditingConditionActions((prev) => ({ ...prev, [cond.id]: true }))}
                                                >
                                                    {!isEditingConditionActions[cond.id] && <span className="bridge-code-edit-label">Click to edit</span>}
                                                    <textarea
                                                        value={cond.action}
                                                        onChange={(event) => updateCondition(cond.id, 'action', event.target.value)}
                                                        onFocus={() => setIsEditingConditionActions((prev) => ({ ...prev, [cond.id]: true }))}
                                                        onBlur={() => setIsEditingConditionActions((prev) => ({ ...prev, [cond.id]: false }))}
                                                        onKeyDown={(event) => handleYamlKeyDown(event, cond.action, (value) => updateCondition(cond.id, 'action', value))}
                                                        className="bridge-code-textarea"
                                                        spellCheck={false}
                                                    />
                                                    <button
                                                        type="button"
                                                        className="bridge-code-expand-btn"
                                                        onClick={(event) => {
                                                            event.stopPropagation();
                                                            openFullscreenEditor('condition-action', cond.id);
                                                        }}
                                                    >
                                                        <Maximize2 size={18} />
                                                    </button>
                                                </div>
                                            </div>
                                        </div>
                                    )}
                                </div>
                            ))}
                        </div>

                        <button type="button" className="bridge-add-condition-btn" onClick={addCondition}>
                            + Add Condition
                        </button>
                    </div>
                ) : (
                    <div className="bridge-processing-code">
                        <div
                            className="bridge-code-editor bridge-processing-editor"
                            onClick={() => setIsEditingProcessingCode(true)}
                        >
                            {!isEditingProcessingCode && <span className="bridge-code-edit-label">Click to edit</span>}
                            <textarea
                                ref={processingCodeRef}
                                className="bridge-code-textarea"
                                value={processingCodeYaml}
                                onChange={(event) => setProcessingCodeYaml(event.target.value)}
                                onFocus={() => setIsEditingProcessingCode(true)}
                                onBlur={(event) => handleProcessingCodeBlur(event.target.value)}
                                onKeyDown={(event) => handleYamlKeyDown(event, processingCodeYaml, setProcessingCodeYaml)}
                                spellCheck={false}
                            />
                            <button
                                type="button"
                                className="bridge-code-expand-btn"
                                onClick={(event) => {
                                    event.stopPropagation();
                                    openFullscreenEditor('processing-code');
                                }}
                            >
                                <Maximize2 size={18} />
                            </button>
                        </div>
                    </div>
                )}
            </div>

            <div className="bridge-readflow-section-card">
                <h2>Output (Unified Namespace)</h2>
                <p>
                    The bridge automatically outputs data to the Unified Namespace, making it available for all connected
                    systems. The output configuration is automatically generated based on your input settings.
                </p>

                <textarea value="(autogenerated)" readOnly />
            </div>

            <div className="bridge-readflow-section-card">
                <h2>YAML Inject (Advanced)</h2>
                <p>
                    Add custom Benthos resources and configurations. Most users won't need this. See the{' '}
                    <a href="https://docs.redpanda.com/redpanda-connect/components/resources/about/" target="_blank" rel="noreferrer">
                        Redpanda Connect resources documentation.
                    </a>
                </p>

                <div
                    className="bridge-code-editor large"
                    onClick={() => setIsEditingInjectYaml(true)}
                >
                    {!isEditingInjectYaml && <span className="bridge-code-edit-label">Click to edit</span>}
                    <textarea
                        ref={injectYamlRef}
                        className="bridge-code-textarea"
                        value={injectYamlValue}
                        onChange={(e) => setInjectYamlValue(e.target.value)}
                        onFocus={() => setIsEditingInjectYaml(true)}
                        onBlur={() => setIsEditingInjectYaml(false)}
                        onKeyDown={(e) => handleYamlKeyDown(e, injectYamlValue, setInjectYamlValue)}
                        spellCheck={false}
                    />
                    <button
                        type="button"
                        className="bridge-code-expand-btn"
                        onClick={(event) => {
                            event.stopPropagation();
                            openFullscreenEditor('inject');
                        }}
                    >
                        <Maximize2 size={18} />
                    </button>
                </div>
            </div>

            {fullscreenEditor.open && (
                <div className="bridge-code-modal-overlay" onClick={closeFullscreenEditor}>
                    <div className="bridge-code-modal" onClick={(event) => event.stopPropagation()}>
                        <div className="bridge-code-modal-header">
                            <h3>{getModalEditorTitle()}</h3>
                            <button
                                type="button"
                                className="bridge-code-modal-close"
                                onClick={closeFullscreenEditor}
                                aria-label="Close fullscreen editor"
                            >
                                <X size={26} />
                            </button>
                        </div>
                        <div className="bridge-code-modal-editor">
                            <pre className="bridge-code-modal-lines">{getLineNumbers(getModalEditorValue())}</pre>
                            <textarea
                                className="bridge-code-modal-textarea"
                                value={getModalEditorValue()}
                                onChange={(event) => setModalEditorValue(event.target.value)}
                                onKeyDown={(event) => handleYamlKeyDown(event, getModalEditorValue(), setModalEditorValue)}
                                spellCheck={false}
                            />
                        </div>
                    </div>
                </div>
            )}

            {pendingDeleteConditionId !== null && (
                <div className="bridge-delete-modal-overlay" onClick={() => setPendingDeleteConditionId(null)}>
                    <div className="bridge-delete-modal" onClick={(event) => event.stopPropagation()}>
                        <button
                            type="button"
                            className="bridge-delete-modal-close"
                            onClick={() => setPendingDeleteConditionId(null)}
                            aria-label="Close delete confirmation"
                        >
                            <X size={34} />
                        </button>

                        <h3>Delete Condition</h3>
                        <p>Are you sure you want to delete this condition? This action cannot be undone.</p>

                        <div className="bridge-delete-modal-actions">
                            <button
                                type="button"
                                className="bridge-modal-cancel-btn"
                                onClick={() => setPendingDeleteConditionId(null)}
                            >
                                Cancel
                            </button>
                            <button
                                type="button"
                                className="bridge-modal-delete-btn"
                                onClick={confirmDeleteCondition}
                            >
                                Delete
                            </button>
                        </div>
                    </div>
                </div>
            )}
        </div>
    );
};

export default EditReadflow;
