package opcua_test

import (
	"os"
	"strings"
	"testing"

	v1 "github.com/artpark-hub/taksa-platform/device-management/api/devicemgmt/v1"
	v2 "github.com/artpark-hub/taksa-platform/device-management/api/umh-core/v2"
	"github.com/artpark-hub/taksa-platform/device-management/internal/protocolconverter/opcua"
	"google.golang.org/protobuf/encoding/protojson"
)

func TestBuildConfigurePayload_fromFixtureShape(t *testing.T) {
	req := &v1.DeployOpcUaProtocolConverterRequest{
		Name: "line-1-opcua-bridge",
		Connection: &v1.ProtocolConverterConnection{
			Ip:   "192.168.1.50",
			Port: 4840,
		},
		Location: &v1.ProtocolConverterLocation{
			Levels: map[int32]string{0: "AcmeCorp", 1: "PlantA"},
		},
		Input: &v1.OpcUaInputSection{
			Mode: v1.EditSectionMode_STRUCTURED,
			Structured: &v1.OpcUaInputStructuredConfig{
				Standard: &v1.OpcUaStandardInputConfig{
					SubscribeEnabled: true,
					UseHeartbeat:     true,
					SubscribeNodeIds: []*v1.OpcUaNodeSubscription{
						{NodeId: "ns=2;s=MyVariable"},
					},
				},
				Advanced: &v1.OpcUaAdvancedInputConfig{
					Profile: "ignition",
				},
			},
		},
		ReadFlow: &v1.OpcUaReadFlowSection{
			DataType:      v1.OpcUaBridgeDataType_TIME_SERIES,
			ProcessorMode: v1.EditSectionMode_STRUCTURED,
			Processor: &v1.OpcUaProcessorStructuredConfig{
				Defaults: &v1.OpcUaProcessorDefaults{
					LocationPath: "PlantA/Line1",
				},
			},
		},
		State: "active",
	}

	pc, err := opcua.BuildConfigurePayload("test-uuid", req.Name, req.Connection, req.Location, req.Input, req.ReadFlow, nil, req.State)
	if err != nil {
		t.Fatal(err)
	}
	if !strings.Contains(pc.ReadDFC.Inputs.Data, "opcua:") {
		t.Fatalf("expected opcua input yaml, got %q", pc.ReadDFC.Inputs.Data)
	}
	if !strings.Contains(pc.ReadDFC.Inputs.Data, "profile:") {
		t.Fatalf("expected profile yaml key, got %q", pc.ReadDFC.Inputs.Data)
	}
	if strings.Contains(pc.ReadDFC.Inputs.Data, "serverProfile") {
		t.Fatal("must not emit legacy serverProfile key")
	}
	if strings.Contains(pc.ReadDFC.Inputs.Data, "subscribeInterval") {
		t.Fatal("must not emit invalid subscribeInterval key")
	}
	if !strings.Contains(pc.ReadDFC.Pipeline.Processors["0"].Data, "tag_processor:") {
		t.Fatalf("expected tag_processor yaml, got %q", pc.ReadDFC.Pipeline.Processors["0"].Data)
	}
	if !strings.Contains(pc.ReadDFC.Pipeline.Processors["0"].Data, "downsampler") {
		// downsampler must not be nested under tag_processor
	} else {
		t.Fatal("downsampler must not be nested under tag_processor")
	}
	if pc.GetState() != "active" {
		t.Fatalf("state: %s", pc.GetState())
	}
	if pc.Meta.Protocol != opcua.ProtocolMetaValue {
		t.Fatalf("meta protocol: %s", pc.Meta.Protocol)
	}
}

func TestToFacade_roundTripFixtureJSON(t *testing.T) {
	raw, err := os.ReadFile("../../../testdata/protocolconverter/fixtures/opcua_get_completed.json")
	if err != nil {
		t.Fatal(err)
	}
	var pc v2.ProtocolConverter
	if err := protojson.Unmarshal(raw, &pc); err != nil {
		t.Fatal(err)
	}
	facade := opcua.ToFacade(&pc)
	if facade.GetUuid() == "" {
		t.Fatal("uuid missing")
	}
	if facade.GetInputParse() != v1.SectionParseStatus_PARSE_OK {
		t.Fatalf("input parse: %v", facade.GetInputParse())
	}
	if !strings.Contains(facade.GetRawInputYaml(), "opcua:") {
		t.Fatal("raw input yaml missing")
	}
	if facade.GetReadFlow() == nil || facade.GetReadFlow().GetProcessor() == nil {
		t.Fatal("read_flow processor missing")
	}
	if !facade.GetOutput().GetAutogenerated() {
		t.Fatal("expected autogenerated output info")
	}
	if facade.GetProtocol() != "opcua" {
		t.Fatalf("protocol: %s", facade.GetProtocol())
	}
}
