package opcua

import (
	"strings"

	v1 "github.com/artpark-hub/taksa-platform/device-management/api/devicemgmt/v1"
	v2 "github.com/artpark-hub/taksa-platform/device-management/api/umh-core/v2"
)

// ToFacade maps umh-core ProtocolConverter to typed OPC-UA facade (structured + raw).
func ToFacade(pc *v2.ProtocolConverter) *v1.OpcUaProtocolConverter {
	if pc == nil {
		return nil
	}
	out := &v1.OpcUaProtocolConverter{
		Uuid:     pc.GetUuid(),
		Name:     pc.GetName(),
		State:    pc.GetState(),
		DataType: v1.BridgeDataType_TIME_SERIES,
		Output: &v1.OpcUaOutputInfo{
			Autogenerated: true,
			Description:   "UNS output is autogenerated on the device for OPC-UA read flows.",
		},
	}
	if pc.Connection != nil {
		out.Connection = &v1.ProtocolConverterConnection{
			Ip:   pc.Connection.GetIp(),
			Port: pc.Connection.GetPort(),
		}
	}
	if len(pc.Location) > 0 {
		out.Location = &v1.ProtocolConverterLocation{Levels: pc.Location}
	}
	if pc.Meta != nil {
		out.ProcessingMode = pc.Meta.GetProcessingMode()
		out.Protocol = pc.Meta.GetProtocol()
		if out.Protocol == "" {
			out.Protocol = ProtocolMetaValue
		}
		if strings.EqualFold(out.ProcessingMode, "timeseries") || out.ProcessingMode == "" {
			out.DataType = v1.BridgeDataType_TIME_SERIES
		}
	}
	if pc.TemplateInfo != nil {
		out.TemplateVariables = map[string]string{}
		for _, v := range pc.TemplateInfo.Variables {
			out.TemplateVariables[v.GetLabel()] = v.GetValue()
		}
	}

	rawInput := ""
	if pc.ReadDFC != nil && pc.ReadDFC.Inputs != nil {
		rawInput = pc.ReadDFC.Inputs.GetData()
	}
	out.RawInputYaml = rawInput

	structuredInput, inputParse := parseInputStructured(rawInput)
	out.Input = &v1.OpcUaInputSection{
		Mode:       inferOpcUaInputMode(inputParse, structuredInput),
		Structured: structuredInput,
		RawYaml:    rawInput,
	}
	out.InputParse = inputParse

	rawProcessor := ""
	rawBuffer := defaultBufferYAML
	if pc.ReadDFC != nil {
		if pc.ReadDFC.Pipeline != nil && pc.ReadDFC.Pipeline.Processors != nil {
			if p := pc.ReadDFC.Pipeline.Processors["0"]; p != nil {
				rawProcessor = p.GetData()
			}
		}
		if pc.ReadDFC.RawYAML != nil {
			rawBuffer = pc.ReadDFC.RawYAML.GetData()
		}
	}
	out.RawProcessorYaml = rawProcessor
	out.RawBufferYaml = rawBuffer

	readFlow, processorParse := parseProcessorStructured(rawProcessor, rawBuffer, out.TemplateVariables)
	out.ReadFlow = readFlow
	out.ProcessorParse = processorParse
	if readFlow != nil && readFlow.GetDataType() != v1.BridgeDataType_BRIDGE_DATA_TYPE_UNSPECIFIED {
		out.DataType = readFlow.GetDataType()
	}

	return out
}

func inferOpcUaInputMode(status v1.SectionParseStatus, cfg *v1.OpcUaInputStructuredConfig) v1.EditSectionMode {
	if status == v1.SectionParseStatus_PARSE_FAILED || cfg == nil {
		return v1.EditSectionMode_RAW
	}
	return v1.EditSectionMode_STRUCTURED
}
