server:
  http:
    addr: 0.0.0.0:8083
    timeout: 1s
  grpc:
    addr: 0.0.0.0:9003
    timeout: 1s

data:
  database:
    driver: postgres
    source: postgres://taksa:taksa_123@172.25.60.23:5433/taksa?sslmode=disable

kratos:
  admin_url: http://172.25.60.23:4434
  public_url: http://172.25.60.23:4433
  