server:
  http:
    addr: 0.0.0.0:8083
    timeout: 1s

data:
  database:
    driver: postgres
    source: postgres://taksa:taksa_123@postgres:5432/taksa?sslmode=disable

  kratos_admin_url: http://taksa-kratos:4434
  kratos_public_url: http://taksa-kratos:4433
