package modbus

import (
	"strconv"
	"strings"

	v1 "github.com/artpark-hub/taksa-platform/device-management/api/devicemgmt/v1"
	v2 "github.com/artpark-hub/taksa-platform/device-management/api/umh-core/v2"
	"github.com/artpark-hub/taksa-platform/device-management/internal/protocolconverter/opcua"
	"github.com/artpark-hub/taksa-platform/device-management/internal/protocolconverter/yamlindent"
)

// ToFacade maps umh-core ProtocolConverter to typed Modbus facade.
func ToFacade(pc *v2.ProtocolConverter) *v1.ModbusProtocolConverter {
	if pc == nil {
		return nil
	}
	out := &v1.ModbusProtocolConverter{
		Uuid:     pc.GetUuid(),
		Name:     pc.GetName(),
		State:    pc.GetState(),
		Output: &v1.OpcUaOutputInfo{
			Autogenerated: true,
			Description:   "UNS output is autogenerated on the device for Modbus read flows.",
		},
	}
	if pc.Connection != nil {
		out.Connection = &v1.ProtocolConverterConnection{
			Ip:   pc.Connection.GetIp(),
			Port: pc.Connection.GetPort(),
		}
	}
	if len(pc.Location) > 0 {
		out.Location = &v1.ProtocolConverterLocation{Levels: pc.Location}
	}
	if pc.Meta != nil {
		out.ProcessingMode = pc.Meta.GetProcessingMode()
		out.Protocol = pc.Meta.GetProtocol()
		if out.Protocol == "" {
			out.Protocol = ProtocolMetaValue
		}
	}
	if pc.TemplateInfo != nil {
		out.TemplateVariables = map[string]string{}
		for _, v := range pc.TemplateInfo.Variables {
			out.TemplateVariables[v.GetLabel()] = v.GetValue()
		}
	}

	rawInput := ""
	if pc.ReadDFC != nil && pc.ReadDFC.Inputs != nil {
		rawInput = pc.ReadDFC.Inputs.GetData()
	}
	out.RawInputYaml = rawInput
	structuredInput, inputParse := parseInputStructured(rawInput)
	out.Input = &v1.ModbusInputSection{
		Mode:       inferInputMode(inputParse, structuredInput),
		Structured: structuredInput,
		RawYaml:    rawInput,
	}
	out.InputParse = inputParse

	rawProcessor := ""
	rawBuffer := defaultBufferYAML
	if pc.ReadDFC != nil {
		if pc.ReadDFC.Pipeline != nil && pc.ReadDFC.Pipeline.Processors != nil {
			if p := pc.ReadDFC.Pipeline.Processors["0"]; p != nil {
				rawProcessor = p.GetData()
			}
		}
		if pc.ReadDFC.RawYAML != nil {
			rawBuffer = pc.ReadDFC.RawYAML.GetData()
		}
	}
	out.RawProcessorYaml = rawProcessor
	out.RawBufferYaml = rawBuffer

	readFlow, processorParse := opcua.ParseReadFlowStructured(rawProcessor, rawBuffer, out.TemplateVariables)
	out.ReadFlow = readFlow
	out.ProcessorParse = processorParse
	out.DataType = bridgeDataTypeFromReadFlow(readFlow)

	return out
}

func bridgeDataTypeFromReadFlow(readFlow *v1.OpcUaReadFlowSection) v1.BridgeDataType {
	if readFlow != nil && readFlow.GetDataType() != v1.BridgeDataType_BRIDGE_DATA_TYPE_UNSPECIFIED {
		return readFlow.GetDataType()
	}
	return v1.BridgeDataType_TIME_SERIES
}

func inferInputMode(status v1.SectionParseStatus, cfg *v1.ModbusInputStructuredConfig) v1.EditSectionMode {
	if status == v1.SectionParseStatus_PARSE_FAILED || cfg == nil {
		return v1.EditSectionMode_RAW
	}
	return v1.EditSectionMode_STRUCTURED
}

func parseInputStructured(raw string) (*v1.ModbusInputStructuredConfig, v1.SectionParseStatus) {
	raw = strings.TrimSpace(raw)
	if raw == "" || !strings.Contains(raw, "modbus:") {
		return nil, v1.SectionParseStatus_PARSE_FAILED
	}

	cfg := &v1.ModbusInputStructuredConfig{
		Standard: &v1.ModbusStandardInputConfig{},
		Advanced: &v1.ModbusAdvancedInputConfig{},
	}
	std := cfg.Standard
	adv := cfg.Advanced
	status := v1.SectionParseStatus_PARSE_OK

	lines := strings.Split(strings.ReplaceAll(raw, "\r\n", "\n"), "\n")
	keyIndent := yamlindent.BlockKeyIndent(lines, "modbus:")
	listItemIndent := keyIndent + 2
	addressEntryIndent := listItemIndent + 2

	inAddresses := false
	var currentAddr *v1.ModbusLegacyAddress

	for i := 0; i < len(lines); i++ {
		rawLine := lines[i]
		trimmed := strings.TrimSpace(rawLine)
		if trimmed == "" || trimmed == "modbus:" || strings.HasPrefix(trimmed, "#") {
			continue
		}
		lineIndent := yamlindent.Leading(rawLine)

		if inAddresses && strings.HasPrefix(trimmed, "- ") && lineIndent >= listItemIndent {
			if currentAddr != nil && legacyAddressPopulated(currentAddr) {
				std.Addresses = append(std.Addresses, currentAddr)
			}
			currentAddr = &v1.ModbusLegacyAddress{}
			rest := strings.TrimSpace(strings.TrimPrefix(trimmed, "- "))
			if strings.Contains(rest, ":") {
				kv := strings.SplitN(rest, ":", 2)
				setLegacyAddressField(currentAddr, strings.TrimSpace(kv[0]), stripYAMLScalar(strings.TrimSpace(kv[1])))
			}
			continue
		}
		if inAddresses && lineIndent >= addressEntryIndent && currentAddr != nil {
			kv := strings.SplitN(trimmed, ":", 2)
			if len(kv) != 2 {
				continue
			}
			setLegacyAddressField(currentAddr, strings.TrimSpace(kv[0]), stripYAMLScalar(strings.TrimSpace(kv[1])))
			continue
		}

		if lineIndent < keyIndent {
			inAddresses = false
			continue
		}
		if lineIndent > keyIndent {
			continue
		}

		sep := strings.Index(trimmed, ":")
		if sep < 0 {
			continue
		}
		yamlKey := strings.TrimSpace(trimmed[:sep])
		rawValue := strings.TrimSpace(trimmed[sep+1:])
		value := stripYAMLScalar(rawValue)

		switch yamlKey {
		case "controller":
			inAddresses = false
			std.Controller = value
		case "slaveIDs":
			inAddresses = false
			if strings.HasPrefix(rawValue, "[") {
				for _, idStr := range parseInlineUintList(rawValue) {
					if n, err := strconv.ParseUint(idStr, 10, 32); err == nil {
						std.SlaveIds = append(std.SlaveIds, uint32(n))
					}
				}
			} else {
				items, last := yamlindent.ListItemsAfterKey(lines, i, keyIndent)
				for _, idStr := range items {
					idStr = stripYAMLScalar(idStr)
					if n, err := strconv.ParseUint(idStr, 10, 32); err == nil {
						std.SlaveIds = append(std.SlaveIds, uint32(n))
					}
				}
				i = last
			}
		case "slaveID":
			inAddresses = false
			if n, err := strconv.ParseUint(value, 10, 32); err == nil {
				std.SlaveIds = append(std.SlaveIds, uint32(n))
			}
		case "unifiedAddresses":
			inAddresses = false
			if rawValue != "" && !strings.HasPrefix(rawValue, "[") {
				std.UnifiedAddresses = append(std.UnifiedAddresses, value)
			}
			items, last := yamlindent.ListItemsAfterKey(lines, i, keyIndent)
			for _, addr := range items {
				addr = stripYAMLScalar(addr)
				if addr != "" {
					std.UnifiedAddresses = append(std.UnifiedAddresses, addr)
				}
			}
			i = last
		case "addresses":
			inAddresses = true
		case "timeBetweenReads":
			inAddresses = false
			std.TimeBetweenReads = value
		case "timeout":
			inAddresses = false
			std.Timeout = value
		case "transmissionMode":
			inAddresses = false
			adv.TransmissionMode = value
		case "optimization":
			inAddresses = false
			adv.Optimization = value
		case "optimizationMaxRegisterFill":
			inAddresses = false
			if n, err := strconv.Atoi(value); err == nil {
				adv.OptimizationMaxRegisterFill = int32(n)
			}
		case "byteOrder":
			inAddresses = false
			adv.ByteOrder = value
		case "busyRetries":
			inAddresses = false
			if n, err := strconv.Atoi(value); err == nil {
				adv.BusyRetries = int32(n)
			}
		case "busyRetriesWait":
			inAddresses = false
			adv.BusyRetriesWait = value
		default:
			inAddresses = false
			cfg.AdditionalSettings = append(cfg.AdditionalSettings, &v1.ModbusAdditionalSetting{
				Key: yamlKey, Value: value,
			})
		}
	}
	if currentAddr != nil && legacyAddressPopulated(currentAddr) {
		std.Addresses = append(std.Addresses, currentAddr)
	}

	if len(std.GetUnifiedAddresses()) == 0 && len(std.GetAddresses()) == 0 {
		status = v1.SectionParseStatus_PARSE_PARTIAL
	}
	return cfg, status
}

func legacyAddressPopulated(a *v1.ModbusLegacyAddress) bool {
	return a.GetName() != "" || a.GetAddress() > 0 || a.GetRegister() != ""
}

func setLegacyAddressField(a *v1.ModbusLegacyAddress, key, val string) {
	switch key {
	case "name":
		a.Name = val
	case "register":
		a.Register = val
	case "address":
		if n, err := strconv.ParseUint(val, 10, 32); err == nil {
			a.Address = uint32(n)
		}
	case "type":
		a.Type = val
	case "length":
		if n, err := strconv.Atoi(val); err == nil {
			a.Length = uint32(n)
		}
	case "bit":
		if n, err := strconv.Atoi(val); err == nil {
			a.Bit = uint32(n)
		}
	case "scale":
		if f, err := strconv.ParseFloat(val, 64); err == nil {
			a.Scale = f
		}
	case "output":
		a.Output = val
	case "slaveID":
		if n, err := strconv.Atoi(val); err == nil {
			a.SlaveId = uint32(n)
		}
	}
}

func parseInlineUintList(raw string) []string {
	raw = stripYAMLScalar(raw)
	if raw == "" || raw == "[]" {
		return nil
	}
	if strings.HasPrefix(raw, "[") && strings.HasSuffix(raw, "]") {
		parts := strings.Split(raw[1:len(raw)-1], ",")
		out := make([]string, 0, len(parts))
		for _, p := range parts {
			p = strings.TrimSpace(p)
			if p != "" {
				out = append(out, p)
			}
		}
		return out
	}
	return nil
}

func stripYAMLScalar(s string) string {
	s = strings.TrimSpace(s)
	if len(s) >= 2 {
		if (s[0] == '"' && s[len(s)-1] == '"') || (s[0] == '\'' && s[len(s)-1] == '\'') {
			unq, err := strconv.Unquote(s)
			if err == nil {
				return unq
			}
		}
	}
	return s
}
