package modbus

import (
	"strconv"
	"strings"

	v1 "github.com/artpark-hub/taksa-platform/device-management/api/devicemgmt/v1"
	v2 "github.com/artpark-hub/taksa-platform/device-management/api/umh-core/v2"
	"github.com/artpark-hub/taksa-platform/device-management/internal/protocolconverter/opcua"
)

// ToFacade maps umh-core ProtocolConverter to typed Modbus facade.
func ToFacade(pc *v2.ProtocolConverter) *v1.ModbusProtocolConverter {
	if pc == nil {
		return nil
	}
	out := &v1.ModbusProtocolConverter{
		Uuid:     pc.GetUuid(),
		Name:     pc.GetName(),
		State:    pc.GetState(),
		DataType: v1.ModbusBridgeDataType_MODBUS_TIME_SERIES,
		Output: &v1.OpcUaOutputInfo{
			Autogenerated: true,
			Description:   "UNS output is autogenerated on the device for Modbus read flows.",
		},
	}
	if pc.Connection != nil {
		out.Connection = &v1.ProtocolConverterConnection{
			Ip:   pc.Connection.GetIp(),
			Port: pc.Connection.GetPort(),
		}
	}
	if len(pc.Location) > 0 {
		out.Location = &v1.ProtocolConverterLocation{Levels: pc.Location}
	}
	if pc.Meta != nil {
		out.ProcessingMode = pc.Meta.GetProcessingMode()
		out.Protocol = pc.Meta.GetProtocol()
		if out.Protocol == "" {
			out.Protocol = ProtocolMetaValue
		}
	}
	if pc.TemplateInfo != nil {
		out.TemplateVariables = map[string]string{}
		for _, v := range pc.TemplateInfo.Variables {
			out.TemplateVariables[v.GetLabel()] = v.GetValue()
		}
	}

	rawInput := ""
	if pc.ReadDFC != nil && pc.ReadDFC.Inputs != nil {
		rawInput = pc.ReadDFC.Inputs.GetData()
	}
	out.RawInputYaml = rawInput
	structuredInput, inputParse := parseInputStructured(rawInput)
	out.Input = &v1.ModbusInputSection{
		Structured: structuredInput,
		RawYaml:    rawInput,
	}
	out.InputParse = inputParse

	rawProcessor := ""
	rawBuffer := defaultBufferYAML
	if pc.ReadDFC != nil {
		if pc.ReadDFC.Pipeline != nil && pc.ReadDFC.Pipeline.Processors != nil {
			if p := pc.ReadDFC.Pipeline.Processors["0"]; p != nil {
				rawProcessor = p.GetData()
			}
		}
		if pc.ReadDFC.RawYAML != nil {
			rawBuffer = pc.ReadDFC.RawYAML.GetData()
		}
	}
	out.RawProcessorYaml = rawProcessor
	out.RawBufferYaml = rawBuffer

	readFlow, processorParse := opcua.ParseReadFlowStructured(rawProcessor, rawBuffer, out.TemplateVariables)
	out.ReadFlow = readFlow
	out.ProcessorParse = processorParse

	return out
}

func parseInputStructured(raw string) (*v1.ModbusInputStructuredConfig, v1.SectionParseStatus) {
	raw = strings.TrimSpace(raw)
	if raw == "" || !strings.Contains(raw, "modbus:") {
		return nil, v1.SectionParseStatus_PARSE_FAILED
	}

	cfg := &v1.ModbusInputStructuredConfig{
		Standard: &v1.ModbusStandardInputConfig{},
		Advanced: &v1.ModbusAdvancedInputConfig{},
	}
	std := cfg.Standard
	adv := cfg.Advanced
	status := v1.SectionParseStatus_PARSE_OK

	lines := strings.Split(strings.ReplaceAll(raw, "\r\n", "\n"), "\n")
	inAddresses := false
	var currentAddr *v1.ModbusLegacyAddress

	for i := 0; i < len(lines); i++ {
		rawLine := lines[i]
		trimmed := strings.TrimSpace(rawLine)
		if trimmed == "" || trimmed == "modbus:" || strings.HasPrefix(trimmed, "#") {
			continue
		}

		if inAddresses && strings.HasPrefix(rawLine, "    -") {
			if currentAddr != nil && currentAddr.GetName() != "" {
				std.Addresses = append(std.Addresses, currentAddr)
			}
			currentAddr = &v1.ModbusLegacyAddress{}
			continue
		}
		if inAddresses && strings.HasPrefix(rawLine, "      ") && currentAddr != nil {
			kv := strings.SplitN(strings.TrimSpace(rawLine), ":", 2)
			if len(kv) != 2 {
				continue
			}
			key := strings.TrimSpace(kv[0])
			val := stripYAMLScalar(strings.TrimSpace(kv[1]))
			switch key {
			case "name":
				currentAddr.Name = val
			case "register":
				currentAddr.Register = val
			case "address":
				if n, err := strconv.ParseUint(val, 10, 32); err == nil {
					currentAddr.Address = uint32(n)
				}
			case "type":
				currentAddr.Type = val
			case "length":
				if n, err := strconv.Atoi(val); err == nil {
					currentAddr.Length = uint32(n)
				}
			case "bit":
				if n, err := strconv.Atoi(val); err == nil {
					currentAddr.Bit = uint32(n)
				}
			case "scale":
				if f, err := strconv.ParseFloat(val, 64); err == nil {
					currentAddr.Scale = f
				}
			case "output":
				currentAddr.Output = val
			case "slaveID":
				if n, err := strconv.Atoi(val); err == nil {
					currentAddr.SlaveId = uint32(n)
				}
			}
			continue
		}
		if !strings.HasPrefix(rawLine, "  ") {
			inAddresses = false
			continue
		}

		sep := strings.Index(trimmed, ":")
		if sep < 0 {
			continue
		}
		yamlKey := strings.TrimSpace(trimmed[:sep])
		rawValue := strings.TrimSpace(trimmed[sep+1:])
		value := stripYAMLScalar(rawValue)

		switch yamlKey {
		case "controller":
			std.Controller = value
		case "slaveIDs":
			if strings.HasPrefix(rawValue, "[") {
				// inline list — skip
				continue
			}
			for i+1 < len(lines) && strings.HasPrefix(lines[i+1], "    -") {
				i++
				idStr := strings.TrimSpace(strings.TrimPrefix(strings.TrimSpace(lines[i]), "-"))
				if n, err := strconv.ParseUint(idStr, 10, 32); err == nil {
					std.SlaveIds = append(std.SlaveIds, uint32(n))
				}
			}
		case "slaveID":
			if n, err := strconv.ParseUint(value, 10, 32); err == nil {
				std.SlaveIds = append(std.SlaveIds, uint32(n))
			}
		case "unifiedAddresses":
			inAddresses = false
			if rawValue != "" && !strings.HasPrefix(rawValue, "[") {
				std.UnifiedAddresses = append(std.UnifiedAddresses, value)
			}
			for i+1 < len(lines) && strings.HasPrefix(lines[i+1], "    -") {
				i++
				addr := strings.TrimSpace(strings.TrimPrefix(strings.TrimSpace(lines[i]), "-"))
				addr = stripYAMLScalar(addr)
				if addr != "" {
					std.UnifiedAddresses = append(std.UnifiedAddresses, addr)
				}
			}
		case "addresses":
			inAddresses = true
		case "timeBetweenReads":
			std.TimeBetweenReads = value
		case "timeout":
			std.Timeout = value
		case "transmissionMode":
			adv.TransmissionMode = value
		case "optimization":
			adv.Optimization = value
		case "optimizationMaxRegisterFill":
			if n, err := strconv.Atoi(value); err == nil {
				adv.OptimizationMaxRegisterFill = int32(n)
			}
		case "byteOrder":
			adv.ByteOrder = value
		case "busyRetries":
			if n, err := strconv.Atoi(value); err == nil {
				adv.BusyRetries = int32(n)
			}
		case "busyRetriesWait":
			adv.BusyRetriesWait = value
		default:
			cfg.AdditionalSettings = append(cfg.AdditionalSettings, &v1.ModbusAdditionalSetting{
				Key: yamlKey, Value: value,
			})
		}
	}
	if currentAddr != nil && currentAddr.GetName() != "" {
		std.Addresses = append(std.Addresses, currentAddr)
	}

	if len(std.GetUnifiedAddresses()) == 0 && len(std.GetAddresses()) == 0 {
		status = v1.SectionParseStatus_PARSE_PARTIAL
	}
	return cfg, status
}

func stripYAMLScalar(s string) string {
	s = strings.TrimSpace(s)
	if len(s) >= 2 {
		if (s[0] == '"' && s[len(s)-1] == '"') || (s[0] == '\'' && s[len(s)-1] == '\'') {
			unq, err := strconv.Unquote(s)
			if err == nil {
				return unq
			}
		}
	}
	return s
}
