// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.9.2
// - protoc             v3.21.12
// source: tenants/v1/tenants.proto

package v1

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationUserManagementServiceCreateSubUser = "/usermanagement.v1.UserManagementService/CreateSubUser"
const OperationUserManagementServiceDeleteMasterUser = "/usermanagement.v1.UserManagementService/DeleteMasterUser"
const OperationUserManagementServiceDeleteSubUser = "/usermanagement.v1.UserManagementService/DeleteSubUser"
const OperationUserManagementServiceGetJWTToken = "/usermanagement.v1.UserManagementService/GetJWTToken"
const OperationUserManagementServiceListSubUsers = "/usermanagement.v1.UserManagementService/ListSubUsers"
const OperationUserManagementServiceUpdateUserProfile = "/usermanagement.v1.UserManagementService/UpdateUserProfile"

type UserManagementServiceHTTPServer interface {
	CreateSubUser(context.Context, *CreateSubUserRequest) (*CreateSubUserResponse, error)
	DeleteMasterUser(context.Context, *DeleteUserRequest) (*DeleteUserResponse, error)
	DeleteSubUser(context.Context, *DeleteUserRequest) (*DeleteUserResponse, error)
	GetJWTToken(context.Context, *GetJWTTokenRequest) (*GetJWTTokenResponse, error)
	ListSubUsers(context.Context, *ListSubUsersRequest) (*ListSubUsersResponse, error)
	UpdateUserProfile(context.Context, *UpdateUserProfileRequest) (*UpdateUserProfileResponse, error)
}

func RegisterUserManagementServiceHTTPServer(s *http.Server, srv UserManagementServiceHTTPServer) {
	r := s.Route("/")
	r.POST("/api/v1/um/create_sub_user", _UserManagementService_CreateSubUser0_HTTP_Handler(srv))
	r.GET("/api/v1/um/list_all_users", _UserManagementService_ListSubUsers0_HTTP_Handler(srv))
	r.DELETE("/api/v1/um/delete_sub_user/{identity_id}", _UserManagementService_DeleteSubUser0_HTTP_Handler(srv))
	r.DELETE("/api/v1/um/delete_master_user/{identity_id}", _UserManagementService_DeleteMasterUser0_HTTP_Handler(srv))
	r.POST("/api/v1/um/update_profile", _UserManagementService_UpdateUserProfile0_HTTP_Handler(srv))
	r.GET("/api/v1/um/token", _UserManagementService_GetJWTToken0_HTTP_Handler(srv))
}

func _UserManagementService_CreateSubUser0_HTTP_Handler(srv UserManagementServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in CreateSubUserRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationUserManagementServiceCreateSubUser)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.CreateSubUser(ctx, req.(*CreateSubUserRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*CreateSubUserResponse)
		return ctx.Result(200, reply)
	}
}

func _UserManagementService_ListSubUsers0_HTTP_Handler(srv UserManagementServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListSubUsersRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationUserManagementServiceListSubUsers)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListSubUsers(ctx, req.(*ListSubUsersRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListSubUsersResponse)
		return ctx.Result(200, reply)
	}
}

func _UserManagementService_DeleteSubUser0_HTTP_Handler(srv UserManagementServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in DeleteUserRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationUserManagementServiceDeleteSubUser)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.DeleteSubUser(ctx, req.(*DeleteUserRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*DeleteUserResponse)
		return ctx.Result(200, reply)
	}
}

func _UserManagementService_DeleteMasterUser0_HTTP_Handler(srv UserManagementServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in DeleteUserRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationUserManagementServiceDeleteMasterUser)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.DeleteMasterUser(ctx, req.(*DeleteUserRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*DeleteUserResponse)
		return ctx.Result(200, reply)
	}
}

func _UserManagementService_UpdateUserProfile0_HTTP_Handler(srv UserManagementServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in UpdateUserProfileRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationUserManagementServiceUpdateUserProfile)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.UpdateUserProfile(ctx, req.(*UpdateUserProfileRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*UpdateUserProfileResponse)
		return ctx.Result(200, reply)
	}
}

func _UserManagementService_GetJWTToken0_HTTP_Handler(srv UserManagementServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetJWTTokenRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationUserManagementServiceGetJWTToken)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetJWTToken(ctx, req.(*GetJWTTokenRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*GetJWTTokenResponse)
		return ctx.Result(200, reply)
	}
}

type UserManagementServiceHTTPClient interface {
	CreateSubUser(ctx context.Context, req *CreateSubUserRequest, opts ...http.CallOption) (rsp *CreateSubUserResponse, err error)
	DeleteMasterUser(ctx context.Context, req *DeleteUserRequest, opts ...http.CallOption) (rsp *DeleteUserResponse, err error)
	DeleteSubUser(ctx context.Context, req *DeleteUserRequest, opts ...http.CallOption) (rsp *DeleteUserResponse, err error)
	GetJWTToken(ctx context.Context, req *GetJWTTokenRequest, opts ...http.CallOption) (rsp *GetJWTTokenResponse, err error)
	ListSubUsers(ctx context.Context, req *ListSubUsersRequest, opts ...http.CallOption) (rsp *ListSubUsersResponse, err error)
	UpdateUserProfile(ctx context.Context, req *UpdateUserProfileRequest, opts ...http.CallOption) (rsp *UpdateUserProfileResponse, err error)
}

type UserManagementServiceHTTPClientImpl struct {
	cc *http.Client
}

func NewUserManagementServiceHTTPClient(client *http.Client) UserManagementServiceHTTPClient {
	return &UserManagementServiceHTTPClientImpl{client}
}

func (c *UserManagementServiceHTTPClientImpl) CreateSubUser(ctx context.Context, in *CreateSubUserRequest, opts ...http.CallOption) (*CreateSubUserResponse, error) {
	var out CreateSubUserResponse
	pattern := "/api/v1/um/create_sub_user"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationUserManagementServiceCreateSubUser))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *UserManagementServiceHTTPClientImpl) DeleteMasterUser(ctx context.Context, in *DeleteUserRequest, opts ...http.CallOption) (*DeleteUserResponse, error) {
	var out DeleteUserResponse
	pattern := "/api/v1/um/delete_master_user/{identity_id}"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationUserManagementServiceDeleteMasterUser))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "DELETE", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *UserManagementServiceHTTPClientImpl) DeleteSubUser(ctx context.Context, in *DeleteUserRequest, opts ...http.CallOption) (*DeleteUserResponse, error) {
	var out DeleteUserResponse
	pattern := "/api/v1/um/delete_sub_user/{identity_id}"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationUserManagementServiceDeleteSubUser))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "DELETE", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *UserManagementServiceHTTPClientImpl) GetJWTToken(ctx context.Context, in *GetJWTTokenRequest, opts ...http.CallOption) (*GetJWTTokenResponse, error) {
	var out GetJWTTokenResponse
	pattern := "/api/v1/um/token"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationUserManagementServiceGetJWTToken))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *UserManagementServiceHTTPClientImpl) ListSubUsers(ctx context.Context, in *ListSubUsersRequest, opts ...http.CallOption) (*ListSubUsersResponse, error) {
	var out ListSubUsersResponse
	pattern := "/api/v1/um/list_all_users"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationUserManagementServiceListSubUsers))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *UserManagementServiceHTTPClientImpl) UpdateUserProfile(ctx context.Context, in *UpdateUserProfileRequest, opts ...http.CallOption) (*UpdateUserProfileResponse, error) {
	var out UpdateUserProfileResponse
	pattern := "/api/v1/um/update_profile"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationUserManagementServiceUpdateUserProfile))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
