// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: tenants/v1/tenants.proto

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateSubUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	FirstName     string                 `protobuf:"bytes,3,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	LastName      string                 `protobuf:"bytes,4,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	Role          string                 `protobuf:"bytes,5,opt,name=role,proto3" json:"role,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateSubUserRequest) Reset() {
	*x = CreateSubUserRequest{}
	mi := &file_tenants_v1_tenants_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSubUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSubUserRequest) ProtoMessage() {}

func (x *CreateSubUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tenants_v1_tenants_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSubUserRequest.ProtoReflect.Descriptor instead.
func (*CreateSubUserRequest) Descriptor() ([]byte, []int) {
	return file_tenants_v1_tenants_proto_rawDescGZIP(), []int{0}
}

func (x *CreateSubUserRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *CreateSubUserRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *CreateSubUserRequest) GetFirstName() string {
	if x != nil {
		return x.FirstName
	}
	return ""
}

func (x *CreateSubUserRequest) GetLastName() string {
	if x != nil {
		return x.LastName
	}
	return ""
}

func (x *CreateSubUserRequest) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

type CreateSubUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          *UserData              `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateSubUserResponse) Reset() {
	*x = CreateSubUserResponse{}
	mi := &file_tenants_v1_tenants_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSubUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSubUserResponse) ProtoMessage() {}

func (x *CreateSubUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tenants_v1_tenants_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSubUserResponse.ProtoReflect.Descriptor instead.
func (*CreateSubUserResponse) Descriptor() ([]byte, []int) {
	return file_tenants_v1_tenants_proto_rawDescGZIP(), []int{1}
}

func (x *CreateSubUserResponse) GetData() *UserData {
	if x != nil {
		return x.Data
	}
	return nil
}

type ListSubUsersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSubUsersRequest) Reset() {
	*x = ListSubUsersRequest{}
	mi := &file_tenants_v1_tenants_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSubUsersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSubUsersRequest) ProtoMessage() {}

func (x *ListSubUsersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tenants_v1_tenants_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSubUsersRequest.ProtoReflect.Descriptor instead.
func (*ListSubUsersRequest) Descriptor() ([]byte, []int) {
	return file_tenants_v1_tenants_proto_rawDescGZIP(), []int{2}
}

type ListSubUsersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Users         []*UserSummary         `protobuf:"bytes,1,rep,name=users,proto3" json:"users,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSubUsersResponse) Reset() {
	*x = ListSubUsersResponse{}
	mi := &file_tenants_v1_tenants_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSubUsersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSubUsersResponse) ProtoMessage() {}

func (x *ListSubUsersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tenants_v1_tenants_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSubUsersResponse.ProtoReflect.Descriptor instead.
func (*ListSubUsersResponse) Descriptor() ([]byte, []int) {
	return file_tenants_v1_tenants_proto_rawDescGZIP(), []int{3}
}

func (x *ListSubUsersResponse) GetUsers() []*UserSummary {
	if x != nil {
		return x.Users
	}
	return nil
}

type DeleteUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IdentityId    string                 `protobuf:"bytes,1,opt,name=identity_id,json=identityId,proto3" json:"identity_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteUserRequest) Reset() {
	*x = DeleteUserRequest{}
	mi := &file_tenants_v1_tenants_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteUserRequest) ProtoMessage() {}

func (x *DeleteUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tenants_v1_tenants_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteUserRequest.ProtoReflect.Descriptor instead.
func (*DeleteUserRequest) Descriptor() ([]byte, []int) {
	return file_tenants_v1_tenants_proto_rawDescGZIP(), []int{4}
}

func (x *DeleteUserRequest) GetIdentityId() string {
	if x != nil {
		return x.IdentityId
	}
	return ""
}

type DeleteUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteUserResponse) Reset() {
	*x = DeleteUserResponse{}
	mi := &file_tenants_v1_tenants_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteUserResponse) ProtoMessage() {}

func (x *DeleteUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tenants_v1_tenants_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteUserResponse.ProtoReflect.Descriptor instead.
func (*DeleteUserResponse) Descriptor() ([]byte, []int) {
	return file_tenants_v1_tenants_proto_rawDescGZIP(), []int{5}
}

func (x *DeleteUserResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *DeleteUserResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type UpdateUserProfileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IdentityId    string                 `protobuf:"bytes,1,opt,name=identity_id,json=identityId,proto3" json:"identity_id,omitempty"`
	FirstName     string                 `protobuf:"bytes,2,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	LastName      string                 `protobuf:"bytes,3,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	Role          string                 `protobuf:"bytes,4,opt,name=role,proto3" json:"role,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateUserProfileRequest) Reset() {
	*x = UpdateUserProfileRequest{}
	mi := &file_tenants_v1_tenants_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateUserProfileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateUserProfileRequest) ProtoMessage() {}

func (x *UpdateUserProfileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tenants_v1_tenants_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateUserProfileRequest.ProtoReflect.Descriptor instead.
func (*UpdateUserProfileRequest) Descriptor() ([]byte, []int) {
	return file_tenants_v1_tenants_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateUserProfileRequest) GetIdentityId() string {
	if x != nil {
		return x.IdentityId
	}
	return ""
}

func (x *UpdateUserProfileRequest) GetFirstName() string {
	if x != nil {
		return x.FirstName
	}
	return ""
}

func (x *UpdateUserProfileRequest) GetLastName() string {
	if x != nil {
		return x.LastName
	}
	return ""
}

func (x *UpdateUserProfileRequest) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

type UpdateUserProfileResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	User          *UserInfo              `protobuf:"bytes,3,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateUserProfileResponse) Reset() {
	*x = UpdateUserProfileResponse{}
	mi := &file_tenants_v1_tenants_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateUserProfileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateUserProfileResponse) ProtoMessage() {}

func (x *UpdateUserProfileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tenants_v1_tenants_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateUserProfileResponse.ProtoReflect.Descriptor instead.
func (*UpdateUserProfileResponse) Descriptor() ([]byte, []int) {
	return file_tenants_v1_tenants_proto_rawDescGZIP(), []int{7}
}

func (x *UpdateUserProfileResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *UpdateUserProfileResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *UpdateUserProfileResponse) GetUser() *UserInfo {
	if x != nil {
		return x.User
	}
	return nil
}

type UserData struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	IdentityId       string                 `protobuf:"bytes,1,opt,name=identity_id,json=identityId,proto3" json:"identity_id,omitempty"`
	OrganizationName string                 `protobuf:"bytes,2,opt,name=organization_name,json=organizationName,proto3" json:"organization_name,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *UserData) Reset() {
	*x = UserData{}
	mi := &file_tenants_v1_tenants_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserData) ProtoMessage() {}

func (x *UserData) ProtoReflect() protoreflect.Message {
	mi := &file_tenants_v1_tenants_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserData.ProtoReflect.Descriptor instead.
func (*UserData) Descriptor() ([]byte, []int) {
	return file_tenants_v1_tenants_proto_rawDescGZIP(), []int{8}
}

func (x *UserData) GetIdentityId() string {
	if x != nil {
		return x.IdentityId
	}
	return ""
}

func (x *UserData) GetOrganizationName() string {
	if x != nil {
		return x.OrganizationName
	}
	return ""
}

type UserSummary struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	IdentityId       string                 `protobuf:"bytes,1,opt,name=identity_id,json=identityId,proto3" json:"identity_id,omitempty"`
	Email            string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	FirstName        string                 `protobuf:"bytes,3,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	LastName         string                 `protobuf:"bytes,4,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	OrganizationName string                 `protobuf:"bytes,5,opt,name=organization_name,json=organizationName,proto3" json:"organization_name,omitempty"`
	Role             string                 `protobuf:"bytes,6,opt,name=role,proto3" json:"role,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *UserSummary) Reset() {
	*x = UserSummary{}
	mi := &file_tenants_v1_tenants_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserSummary) ProtoMessage() {}

func (x *UserSummary) ProtoReflect() protoreflect.Message {
	mi := &file_tenants_v1_tenants_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserSummary.ProtoReflect.Descriptor instead.
func (*UserSummary) Descriptor() ([]byte, []int) {
	return file_tenants_v1_tenants_proto_rawDescGZIP(), []int{9}
}

func (x *UserSummary) GetIdentityId() string {
	if x != nil {
		return x.IdentityId
	}
	return ""
}

func (x *UserSummary) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *UserSummary) GetFirstName() string {
	if x != nil {
		return x.FirstName
	}
	return ""
}

func (x *UserSummary) GetLastName() string {
	if x != nil {
		return x.LastName
	}
	return ""
}

func (x *UserSummary) GetOrganizationName() string {
	if x != nil {
		return x.OrganizationName
	}
	return ""
}

func (x *UserSummary) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

type UserInfo struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Email            string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	FirstName        string                 `protobuf:"bytes,2,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	LastName         string                 `protobuf:"bytes,3,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	OrganizationName string                 `protobuf:"bytes,4,opt,name=organization_name,json=organizationName,proto3" json:"organization_name,omitempty"`
	Role             string                 `protobuf:"bytes,5,opt,name=role,proto3" json:"role,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *UserInfo) Reset() {
	*x = UserInfo{}
	mi := &file_tenants_v1_tenants_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserInfo) ProtoMessage() {}

func (x *UserInfo) ProtoReflect() protoreflect.Message {
	mi := &file_tenants_v1_tenants_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserInfo.ProtoReflect.Descriptor instead.
func (*UserInfo) Descriptor() ([]byte, []int) {
	return file_tenants_v1_tenants_proto_rawDescGZIP(), []int{10}
}

func (x *UserInfo) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *UserInfo) GetFirstName() string {
	if x != nil {
		return x.FirstName
	}
	return ""
}

func (x *UserInfo) GetLastName() string {
	if x != nil {
		return x.LastName
	}
	return ""
}

func (x *UserInfo) GetOrganizationName() string {
	if x != nil {
		return x.OrganizationName
	}
	return ""
}

func (x *UserInfo) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

type GetJWTTokenRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetJWTTokenRequest) Reset() {
	*x = GetJWTTokenRequest{}
	mi := &file_tenants_v1_tenants_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetJWTTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetJWTTokenRequest) ProtoMessage() {}

func (x *GetJWTTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tenants_v1_tenants_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetJWTTokenRequest.ProtoReflect.Descriptor instead.
func (*GetJWTTokenRequest) Descriptor() ([]byte, []int) {
	return file_tenants_v1_tenants_proto_rawDescGZIP(), []int{11}
}

type GetJWTTokenResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          *TokenData             `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetJWTTokenResponse) Reset() {
	*x = GetJWTTokenResponse{}
	mi := &file_tenants_v1_tenants_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetJWTTokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetJWTTokenResponse) ProtoMessage() {}

func (x *GetJWTTokenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tenants_v1_tenants_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetJWTTokenResponse.ProtoReflect.Descriptor instead.
func (*GetJWTTokenResponse) Descriptor() ([]byte, []int) {
	return file_tenants_v1_tenants_proto_rawDescGZIP(), []int{12}
}

func (x *GetJWTTokenResponse) GetData() *TokenData {
	if x != nil {
		return x.Data
	}
	return nil
}

type TokenData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JwtToken      string                 `protobuf:"bytes,1,opt,name=jwt_token,json=jwtToken,proto3" json:"jwt_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TokenData) Reset() {
	*x = TokenData{}
	mi := &file_tenants_v1_tenants_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TokenData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TokenData) ProtoMessage() {}

func (x *TokenData) ProtoReflect() protoreflect.Message {
	mi := &file_tenants_v1_tenants_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TokenData.ProtoReflect.Descriptor instead.
func (*TokenData) Descriptor() ([]byte, []int) {
	return file_tenants_v1_tenants_proto_rawDescGZIP(), []int{13}
}

func (x *TokenData) GetJwtToken() string {
	if x != nil {
		return x.JwtToken
	}
	return ""
}

var File_tenants_v1_tenants_proto protoreflect.FileDescriptor

const file_tenants_v1_tenants_proto_rawDesc = "" +
	"\n" +
	"\x18tenants/v1/tenants.proto\x12\x11usermanagement.v1\x1a\x1cgoogle/api/annotations.proto\"\x98\x01\n" +
	"\x14CreateSubUserRequest\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\x12\x1d\n" +
	"\n" +
	"first_name\x18\x03 \x01(\tR\tfirstName\x12\x1b\n" +
	"\tlast_name\x18\x04 \x01(\tR\blastName\x12\x12\n" +
	"\x04role\x18\x05 \x01(\tR\x04role\"H\n" +
	"\x15CreateSubUserResponse\x12/\n" +
	"\x04data\x18\x01 \x01(\v2\x1b.usermanagement.v1.UserDataR\x04data\"\x15\n" +
	"\x13ListSubUsersRequest\"L\n" +
	"\x14ListSubUsersResponse\x124\n" +
	"\x05users\x18\x01 \x03(\v2\x1e.usermanagement.v1.UserSummaryR\x05users\"4\n" +
	"\x11DeleteUserRequest\x12\x1f\n" +
	"\videntity_id\x18\x01 \x01(\tR\n" +
	"identityId\"F\n" +
	"\x12DeleteUserResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\x8b\x01\n" +
	"\x18UpdateUserProfileRequest\x12\x1f\n" +
	"\videntity_id\x18\x01 \x01(\tR\n" +
	"identityId\x12\x1d\n" +
	"\n" +
	"first_name\x18\x02 \x01(\tR\tfirstName\x12\x1b\n" +
	"\tlast_name\x18\x03 \x01(\tR\blastName\x12\x12\n" +
	"\x04role\x18\x04 \x01(\tR\x04role\"~\n" +
	"\x19UpdateUserProfileResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12/\n" +
	"\x04user\x18\x03 \x01(\v2\x1b.usermanagement.v1.UserInfoR\x04user\"X\n" +
	"\bUserData\x12\x1f\n" +
	"\videntity_id\x18\x01 \x01(\tR\n" +
	"identityId\x12+\n" +
	"\x11organization_name\x18\x02 \x01(\tR\x10organizationName\"\xc1\x01\n" +
	"\vUserSummary\x12\x1f\n" +
	"\videntity_id\x18\x01 \x01(\tR\n" +
	"identityId\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\x12\x1d\n" +
	"\n" +
	"first_name\x18\x03 \x01(\tR\tfirstName\x12\x1b\n" +
	"\tlast_name\x18\x04 \x01(\tR\blastName\x12+\n" +
	"\x11organization_name\x18\x05 \x01(\tR\x10organizationName\x12\x12\n" +
	"\x04role\x18\x06 \x01(\tR\x04role\"\x9d\x01\n" +
	"\bUserInfo\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\x12\x1d\n" +
	"\n" +
	"first_name\x18\x02 \x01(\tR\tfirstName\x12\x1b\n" +
	"\tlast_name\x18\x03 \x01(\tR\blastName\x12+\n" +
	"\x11organization_name\x18\x04 \x01(\tR\x10organizationName\x12\x12\n" +
	"\x04role\x18\x05 \x01(\tR\x04role\"\x14\n" +
	"\x12GetJWTTokenRequest\"G\n" +
	"\x13GetJWTTokenResponse\x120\n" +
	"\x04data\x18\x01 \x01(\v2\x1c.usermanagement.v1.TokenDataR\x04data\"(\n" +
	"\tTokenData\x12\x1b\n" +
	"\tjwt_token\x18\x01 \x01(\tR\bjwtToken2\xdf\x06\n" +
	"\x15UserManagementService\x12\x89\x01\n" +
	"\rCreateSubUser\x12'.usermanagement.v1.CreateSubUserRequest\x1a(.usermanagement.v1.CreateSubUserResponse\"%\x82\xd3\xe4\x93\x02\x1f:\x01*\"\x1a/api/v1/um/create_sub_user\x12\x82\x01\n" +
	"\fListSubUsers\x12&.usermanagement.v1.ListSubUsersRequest\x1a'.usermanagement.v1.ListSubUsersResponse\"!\x82\xd3\xe4\x93\x02\x1b\x12\x19/api/v1/um/list_all_users\x12\x8e\x01\n" +
	"\rDeleteSubUser\x12$.usermanagement.v1.DeleteUserRequest\x1a%.usermanagement.v1.DeleteUserResponse\"0\x82\xd3\xe4\x93\x02**(/api/v1/um/delete_sub_user/{identity_id}\x12\x94\x01\n" +
	"\x10DeleteMasterUser\x12$.usermanagement.v1.DeleteUserRequest\x1a%.usermanagement.v1.DeleteUserResponse\"3\x82\xd3\xe4\x93\x02-*+/api/v1/um/delete_master_user/{identity_id}\x12\x94\x01\n" +
	"\x11UpdateUserProfile\x12+.usermanagement.v1.UpdateUserProfileRequest\x1a,.usermanagement.v1.UpdateUserProfileResponse\"$\x82\xd3\xe4\x93\x02\x1e:\x01*\"\x19/api/v1/um/update_profile\x12v\n" +
	"\vGetJWTToken\x12%.usermanagement.v1.GetJWTTokenRequest\x1a&.usermanagement.v1.GetJWTTokenResponse\"\x18\x82\xd3\xe4\x93\x02\x12\x12\x10/api/v1/um/tokenB#Z!user-management/api/tenants/v1;v1b\x06proto3"

var (
	file_tenants_v1_tenants_proto_rawDescOnce sync.Once
	file_tenants_v1_tenants_proto_rawDescData []byte
)

func file_tenants_v1_tenants_proto_rawDescGZIP() []byte {
	file_tenants_v1_tenants_proto_rawDescOnce.Do(func() {
		file_tenants_v1_tenants_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_tenants_v1_tenants_proto_rawDesc), len(file_tenants_v1_tenants_proto_rawDesc)))
	})
	return file_tenants_v1_tenants_proto_rawDescData
}

var file_tenants_v1_tenants_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_tenants_v1_tenants_proto_goTypes = []any{
	(*CreateSubUserRequest)(nil),      // 0: usermanagement.v1.CreateSubUserRequest
	(*CreateSubUserResponse)(nil),     // 1: usermanagement.v1.CreateSubUserResponse
	(*ListSubUsersRequest)(nil),       // 2: usermanagement.v1.ListSubUsersRequest
	(*ListSubUsersResponse)(nil),      // 3: usermanagement.v1.ListSubUsersResponse
	(*DeleteUserRequest)(nil),         // 4: usermanagement.v1.DeleteUserRequest
	(*DeleteUserResponse)(nil),        // 5: usermanagement.v1.DeleteUserResponse
	(*UpdateUserProfileRequest)(nil),  // 6: usermanagement.v1.UpdateUserProfileRequest
	(*UpdateUserProfileResponse)(nil), // 7: usermanagement.v1.UpdateUserProfileResponse
	(*UserData)(nil),                  // 8: usermanagement.v1.UserData
	(*UserSummary)(nil),               // 9: usermanagement.v1.UserSummary
	(*UserInfo)(nil),                  // 10: usermanagement.v1.UserInfo
	(*GetJWTTokenRequest)(nil),        // 11: usermanagement.v1.GetJWTTokenRequest
	(*GetJWTTokenResponse)(nil),       // 12: usermanagement.v1.GetJWTTokenResponse
	(*TokenData)(nil),                 // 13: usermanagement.v1.TokenData
}
var file_tenants_v1_tenants_proto_depIdxs = []int32{
	8,  // 0: usermanagement.v1.CreateSubUserResponse.data:type_name -> usermanagement.v1.UserData
	9,  // 1: usermanagement.v1.ListSubUsersResponse.users:type_name -> usermanagement.v1.UserSummary
	10, // 2: usermanagement.v1.UpdateUserProfileResponse.user:type_name -> usermanagement.v1.UserInfo
	13, // 3: usermanagement.v1.GetJWTTokenResponse.data:type_name -> usermanagement.v1.TokenData
	0,  // 4: usermanagement.v1.UserManagementService.CreateSubUser:input_type -> usermanagement.v1.CreateSubUserRequest
	2,  // 5: usermanagement.v1.UserManagementService.ListSubUsers:input_type -> usermanagement.v1.ListSubUsersRequest
	4,  // 6: usermanagement.v1.UserManagementService.DeleteSubUser:input_type -> usermanagement.v1.DeleteUserRequest
	4,  // 7: usermanagement.v1.UserManagementService.DeleteMasterUser:input_type -> usermanagement.v1.DeleteUserRequest
	6,  // 8: usermanagement.v1.UserManagementService.UpdateUserProfile:input_type -> usermanagement.v1.UpdateUserProfileRequest
	11, // 9: usermanagement.v1.UserManagementService.GetJWTToken:input_type -> usermanagement.v1.GetJWTTokenRequest
	1,  // 10: usermanagement.v1.UserManagementService.CreateSubUser:output_type -> usermanagement.v1.CreateSubUserResponse
	3,  // 11: usermanagement.v1.UserManagementService.ListSubUsers:output_type -> usermanagement.v1.ListSubUsersResponse
	5,  // 12: usermanagement.v1.UserManagementService.DeleteSubUser:output_type -> usermanagement.v1.DeleteUserResponse
	5,  // 13: usermanagement.v1.UserManagementService.DeleteMasterUser:output_type -> usermanagement.v1.DeleteUserResponse
	7,  // 14: usermanagement.v1.UserManagementService.UpdateUserProfile:output_type -> usermanagement.v1.UpdateUserProfileResponse
	12, // 15: usermanagement.v1.UserManagementService.GetJWTToken:output_type -> usermanagement.v1.GetJWTTokenResponse
	10, // [10:16] is the sub-list for method output_type
	4,  // [4:10] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_tenants_v1_tenants_proto_init() }
func file_tenants_v1_tenants_proto_init() {
	if File_tenants_v1_tenants_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_tenants_v1_tenants_proto_rawDesc), len(file_tenants_v1_tenants_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_tenants_v1_tenants_proto_goTypes,
		DependencyIndexes: file_tenants_v1_tenants_proto_depIdxs,
		MessageInfos:      file_tenants_v1_tenants_proto_msgTypes,
	}.Build()
	File_tenants_v1_tenants_proto = out.File
	file_tenants_v1_tenants_proto_goTypes = nil
	file_tenants_v1_tenants_proto_depIdxs = nil
}
