// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.1
// source: tenants/v1/tenants.proto

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RegisterMasterUserRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Email            string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Password         string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	FirstName        string                 `protobuf:"bytes,3,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	LastName         string                 `protobuf:"bytes,4,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	OrganizationName string                 `protobuf:"bytes,5,opt,name=organization_name,json=organizationName,proto3" json:"organization_name,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *RegisterMasterUserRequest) Reset() {
	*x = RegisterMasterUserRequest{}
	mi := &file_tenants_v1_tenants_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterMasterUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterMasterUserRequest) ProtoMessage() {}

func (x *RegisterMasterUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tenants_v1_tenants_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterMasterUserRequest.ProtoReflect.Descriptor instead.
func (*RegisterMasterUserRequest) Descriptor() ([]byte, []int) {
	return file_tenants_v1_tenants_proto_rawDescGZIP(), []int{0}
}

func (x *RegisterMasterUserRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *RegisterMasterUserRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *RegisterMasterUserRequest) GetFirstName() string {
	if x != nil {
		return x.FirstName
	}
	return ""
}

func (x *RegisterMasterUserRequest) GetLastName() string {
	if x != nil {
		return x.LastName
	}
	return ""
}

func (x *RegisterMasterUserRequest) GetOrganizationName() string {
	if x != nil {
		return x.OrganizationName
	}
	return ""
}

type RegisterMasterUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          *TenantData            `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterMasterUserResponse) Reset() {
	*x = RegisterMasterUserResponse{}
	mi := &file_tenants_v1_tenants_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterMasterUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterMasterUserResponse) ProtoMessage() {}

func (x *RegisterMasterUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tenants_v1_tenants_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterMasterUserResponse.ProtoReflect.Descriptor instead.
func (*RegisterMasterUserResponse) Descriptor() ([]byte, []int) {
	return file_tenants_v1_tenants_proto_rawDescGZIP(), []int{1}
}

func (x *RegisterMasterUserResponse) GetData() *TenantData {
	if x != nil {
		return x.Data
	}
	return nil
}

type LoginUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginUserRequest) Reset() {
	*x = LoginUserRequest{}
	mi := &file_tenants_v1_tenants_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginUserRequest) ProtoMessage() {}

func (x *LoginUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tenants_v1_tenants_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginUserRequest.ProtoReflect.Descriptor instead.
func (*LoginUserRequest) Descriptor() ([]byte, []int) {
	return file_tenants_v1_tenants_proto_rawDescGZIP(), []int{2}
}

func (x *LoginUserRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *LoginUserRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type LoginUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionToken  string                 `protobuf:"bytes,1,opt,name=session_token,json=sessionToken,proto3" json:"session_token,omitempty"`
	User          *UserInfo              `protobuf:"bytes,2,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginUserResponse) Reset() {
	*x = LoginUserResponse{}
	mi := &file_tenants_v1_tenants_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginUserResponse) ProtoMessage() {}

func (x *LoginUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tenants_v1_tenants_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginUserResponse.ProtoReflect.Descriptor instead.
func (*LoginUserResponse) Descriptor() ([]byte, []int) {
	return file_tenants_v1_tenants_proto_rawDescGZIP(), []int{3}
}

func (x *LoginUserResponse) GetSessionToken() string {
	if x != nil {
		return x.SessionToken
	}
	return ""
}

func (x *LoginUserResponse) GetUser() *UserInfo {
	if x != nil {
		return x.User
	}
	return nil
}

type UserInfo struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Email            string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	FirstName        string                 `protobuf:"bytes,2,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	LastName         string                 `protobuf:"bytes,3,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	OrganizationName string                 `protobuf:"bytes,4,opt,name=organization_name,json=organizationName,proto3" json:"organization_name,omitempty"`
	Role             string                 `protobuf:"bytes,5,opt,name=role,proto3" json:"role,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *UserInfo) Reset() {
	*x = UserInfo{}
	mi := &file_tenants_v1_tenants_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserInfo) ProtoMessage() {}

func (x *UserInfo) ProtoReflect() protoreflect.Message {
	mi := &file_tenants_v1_tenants_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserInfo.ProtoReflect.Descriptor instead.
func (*UserInfo) Descriptor() ([]byte, []int) {
	return file_tenants_v1_tenants_proto_rawDescGZIP(), []int{4}
}

func (x *UserInfo) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *UserInfo) GetFirstName() string {
	if x != nil {
		return x.FirstName
	}
	return ""
}

func (x *UserInfo) GetLastName() string {
	if x != nil {
		return x.LastName
	}
	return ""
}

func (x *UserInfo) GetOrganizationName() string {
	if x != nil {
		return x.OrganizationName
	}
	return ""
}

func (x *UserInfo) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

type GetJWTTokenRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetJWTTokenRequest) Reset() {
	*x = GetJWTTokenRequest{}
	mi := &file_tenants_v1_tenants_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetJWTTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetJWTTokenRequest) ProtoMessage() {}

func (x *GetJWTTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tenants_v1_tenants_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetJWTTokenRequest.ProtoReflect.Descriptor instead.
func (*GetJWTTokenRequest) Descriptor() ([]byte, []int) {
	return file_tenants_v1_tenants_proto_rawDescGZIP(), []int{5}
}

type GetJWTTokenResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          *TokenData             `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetJWTTokenResponse) Reset() {
	*x = GetJWTTokenResponse{}
	mi := &file_tenants_v1_tenants_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetJWTTokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetJWTTokenResponse) ProtoMessage() {}

func (x *GetJWTTokenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tenants_v1_tenants_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetJWTTokenResponse.ProtoReflect.Descriptor instead.
func (*GetJWTTokenResponse) Descriptor() ([]byte, []int) {
	return file_tenants_v1_tenants_proto_rawDescGZIP(), []int{6}
}

func (x *GetJWTTokenResponse) GetData() *TokenData {
	if x != nil {
		return x.Data
	}
	return nil
}

type CreateSubUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	FirstName     string                 `protobuf:"bytes,3,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	LastName      string                 `protobuf:"bytes,4,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateSubUserRequest) Reset() {
	*x = CreateSubUserRequest{}
	mi := &file_tenants_v1_tenants_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSubUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSubUserRequest) ProtoMessage() {}

func (x *CreateSubUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tenants_v1_tenants_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSubUserRequest.ProtoReflect.Descriptor instead.
func (*CreateSubUserRequest) Descriptor() ([]byte, []int) {
	return file_tenants_v1_tenants_proto_rawDescGZIP(), []int{7}
}

func (x *CreateSubUserRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *CreateSubUserRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *CreateSubUserRequest) GetFirstName() string {
	if x != nil {
		return x.FirstName
	}
	return ""
}

func (x *CreateSubUserRequest) GetLastName() string {
	if x != nil {
		return x.LastName
	}
	return ""
}

type CreateSubUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          *UserData              `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateSubUserResponse) Reset() {
	*x = CreateSubUserResponse{}
	mi := &file_tenants_v1_tenants_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSubUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSubUserResponse) ProtoMessage() {}

func (x *CreateSubUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tenants_v1_tenants_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSubUserResponse.ProtoReflect.Descriptor instead.
func (*CreateSubUserResponse) Descriptor() ([]byte, []int) {
	return file_tenants_v1_tenants_proto_rawDescGZIP(), []int{8}
}

func (x *CreateSubUserResponse) GetData() *UserData {
	if x != nil {
		return x.Data
	}
	return nil
}

type ListSubUsersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSubUsersRequest) Reset() {
	*x = ListSubUsersRequest{}
	mi := &file_tenants_v1_tenants_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSubUsersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSubUsersRequest) ProtoMessage() {}

func (x *ListSubUsersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tenants_v1_tenants_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSubUsersRequest.ProtoReflect.Descriptor instead.
func (*ListSubUsersRequest) Descriptor() ([]byte, []int) {
	return file_tenants_v1_tenants_proto_rawDescGZIP(), []int{9}
}

type ListSubUsersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Users         []*UserSummary         `protobuf:"bytes,1,rep,name=users,proto3" json:"users,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSubUsersResponse) Reset() {
	*x = ListSubUsersResponse{}
	mi := &file_tenants_v1_tenants_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSubUsersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSubUsersResponse) ProtoMessage() {}

func (x *ListSubUsersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tenants_v1_tenants_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSubUsersResponse.ProtoReflect.Descriptor instead.
func (*ListSubUsersResponse) Descriptor() ([]byte, []int) {
	return file_tenants_v1_tenants_proto_rawDescGZIP(), []int{10}
}

func (x *ListSubUsersResponse) GetUsers() []*UserSummary {
	if x != nil {
		return x.Users
	}
	return nil
}

type DeleteUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IdentityId    string                 `protobuf:"bytes,1,opt,name=identity_id,json=identityId,proto3" json:"identity_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteUserRequest) Reset() {
	*x = DeleteUserRequest{}
	mi := &file_tenants_v1_tenants_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteUserRequest) ProtoMessage() {}

func (x *DeleteUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tenants_v1_tenants_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteUserRequest.ProtoReflect.Descriptor instead.
func (*DeleteUserRequest) Descriptor() ([]byte, []int) {
	return file_tenants_v1_tenants_proto_rawDescGZIP(), []int{11}
}

func (x *DeleteUserRequest) GetIdentityId() string {
	if x != nil {
		return x.IdentityId
	}
	return ""
}

type DeleteUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteUserResponse) Reset() {
	*x = DeleteUserResponse{}
	mi := &file_tenants_v1_tenants_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteUserResponse) ProtoMessage() {}

func (x *DeleteUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tenants_v1_tenants_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteUserResponse.ProtoReflect.Descriptor instead.
func (*DeleteUserResponse) Descriptor() ([]byte, []int) {
	return file_tenants_v1_tenants_proto_rawDescGZIP(), []int{12}
}

func (x *DeleteUserResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *DeleteUserResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type TenantData struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	IdentityId       string                 `protobuf:"bytes,1,opt,name=identity_id,json=identityId,proto3" json:"identity_id,omitempty"`
	OrganizationName string                 `protobuf:"bytes,2,opt,name=organization_name,json=organizationName,proto3" json:"organization_name,omitempty"`
	Status           string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *TenantData) Reset() {
	*x = TenantData{}
	mi := &file_tenants_v1_tenants_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TenantData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TenantData) ProtoMessage() {}

func (x *TenantData) ProtoReflect() protoreflect.Message {
	mi := &file_tenants_v1_tenants_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TenantData.ProtoReflect.Descriptor instead.
func (*TenantData) Descriptor() ([]byte, []int) {
	return file_tenants_v1_tenants_proto_rawDescGZIP(), []int{13}
}

func (x *TenantData) GetIdentityId() string {
	if x != nil {
		return x.IdentityId
	}
	return ""
}

func (x *TenantData) GetOrganizationName() string {
	if x != nil {
		return x.OrganizationName
	}
	return ""
}

func (x *TenantData) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type TokenData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JwtToken      string                 `protobuf:"bytes,1,opt,name=jwt_token,json=jwtToken,proto3" json:"jwt_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TokenData) Reset() {
	*x = TokenData{}
	mi := &file_tenants_v1_tenants_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TokenData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TokenData) ProtoMessage() {}

func (x *TokenData) ProtoReflect() protoreflect.Message {
	mi := &file_tenants_v1_tenants_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TokenData.ProtoReflect.Descriptor instead.
func (*TokenData) Descriptor() ([]byte, []int) {
	return file_tenants_v1_tenants_proto_rawDescGZIP(), []int{14}
}

func (x *TokenData) GetJwtToken() string {
	if x != nil {
		return x.JwtToken
	}
	return ""
}

type UserData struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	IdentityId       string                 `protobuf:"bytes,1,opt,name=identity_id,json=identityId,proto3" json:"identity_id,omitempty"`
	OrganizationName string                 `protobuf:"bytes,2,opt,name=organization_name,json=organizationName,proto3" json:"organization_name,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *UserData) Reset() {
	*x = UserData{}
	mi := &file_tenants_v1_tenants_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserData) ProtoMessage() {}

func (x *UserData) ProtoReflect() protoreflect.Message {
	mi := &file_tenants_v1_tenants_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserData.ProtoReflect.Descriptor instead.
func (*UserData) Descriptor() ([]byte, []int) {
	return file_tenants_v1_tenants_proto_rawDescGZIP(), []int{15}
}

func (x *UserData) GetIdentityId() string {
	if x != nil {
		return x.IdentityId
	}
	return ""
}

func (x *UserData) GetOrganizationName() string {
	if x != nil {
		return x.OrganizationName
	}
	return ""
}

type UserSummary struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	IdentityId       string                 `protobuf:"bytes,1,opt,name=identity_id,json=identityId,proto3" json:"identity_id,omitempty"`
	Email            string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	FirstName        string                 `protobuf:"bytes,3,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	LastName         string                 `protobuf:"bytes,4,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	OrganizationName string                 `protobuf:"bytes,5,opt,name=organization_name,json=organizationName,proto3" json:"organization_name,omitempty"`
	Role             string                 `protobuf:"bytes,6,opt,name=role,proto3" json:"role,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *UserSummary) Reset() {
	*x = UserSummary{}
	mi := &file_tenants_v1_tenants_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserSummary) ProtoMessage() {}

func (x *UserSummary) ProtoReflect() protoreflect.Message {
	mi := &file_tenants_v1_tenants_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserSummary.ProtoReflect.Descriptor instead.
func (*UserSummary) Descriptor() ([]byte, []int) {
	return file_tenants_v1_tenants_proto_rawDescGZIP(), []int{16}
}

func (x *UserSummary) GetIdentityId() string {
	if x != nil {
		return x.IdentityId
	}
	return ""
}

func (x *UserSummary) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *UserSummary) GetFirstName() string {
	if x != nil {
		return x.FirstName
	}
	return ""
}

func (x *UserSummary) GetLastName() string {
	if x != nil {
		return x.LastName
	}
	return ""
}

func (x *UserSummary) GetOrganizationName() string {
	if x != nil {
		return x.OrganizationName
	}
	return ""
}

func (x *UserSummary) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

var File_tenants_v1_tenants_proto protoreflect.FileDescriptor

const file_tenants_v1_tenants_proto_rawDesc = "" +
	"\n" +
	"\x18tenants/v1/tenants.proto\x12\n" +
	"tenants.v1\x1a\x1cgoogle/api/annotations.proto\"\xb6\x01\n" +
	"\x19RegisterMasterUserRequest\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\x12\x1d\n" +
	"\n" +
	"first_name\x18\x03 \x01(\tR\tfirstName\x12\x1b\n" +
	"\tlast_name\x18\x04 \x01(\tR\blastName\x12+\n" +
	"\x11organization_name\x18\x05 \x01(\tR\x10organizationName\"H\n" +
	"\x1aRegisterMasterUserResponse\x12*\n" +
	"\x04data\x18\x01 \x01(\v2\x16.tenants.v1.TenantDataR\x04data\"D\n" +
	"\x10LoginUserRequest\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"b\n" +
	"\x11LoginUserResponse\x12#\n" +
	"\rsession_token\x18\x01 \x01(\tR\fsessionToken\x12(\n" +
	"\x04user\x18\x02 \x01(\v2\x14.tenants.v1.UserInfoR\x04user\"\x9d\x01\n" +
	"\bUserInfo\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\x12\x1d\n" +
	"\n" +
	"first_name\x18\x02 \x01(\tR\tfirstName\x12\x1b\n" +
	"\tlast_name\x18\x03 \x01(\tR\blastName\x12+\n" +
	"\x11organization_name\x18\x04 \x01(\tR\x10organizationName\x12\x12\n" +
	"\x04role\x18\x05 \x01(\tR\x04role\"\x14\n" +
	"\x12GetJWTTokenRequest\"@\n" +
	"\x13GetJWTTokenResponse\x12)\n" +
	"\x04data\x18\x01 \x01(\v2\x15.tenants.v1.TokenDataR\x04data\"\x84\x01\n" +
	"\x14CreateSubUserRequest\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\x12\x1d\n" +
	"\n" +
	"first_name\x18\x03 \x01(\tR\tfirstName\x12\x1b\n" +
	"\tlast_name\x18\x04 \x01(\tR\blastName\"A\n" +
	"\x15CreateSubUserResponse\x12(\n" +
	"\x04data\x18\x01 \x01(\v2\x14.tenants.v1.UserDataR\x04data\"\x15\n" +
	"\x13ListSubUsersRequest\"E\n" +
	"\x14ListSubUsersResponse\x12-\n" +
	"\x05users\x18\x01 \x03(\v2\x17.tenants.v1.UserSummaryR\x05users\"4\n" +
	"\x11DeleteUserRequest\x12\x1f\n" +
	"\videntity_id\x18\x01 \x01(\tR\n" +
	"identityId\"F\n" +
	"\x12DeleteUserResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"r\n" +
	"\n" +
	"TenantData\x12\x1f\n" +
	"\videntity_id\x18\x01 \x01(\tR\n" +
	"identityId\x12+\n" +
	"\x11organization_name\x18\x02 \x01(\tR\x10organizationName\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\"(\n" +
	"\tTokenData\x12\x1b\n" +
	"\tjwt_token\x18\x01 \x01(\tR\bjwtToken\"X\n" +
	"\bUserData\x12\x1f\n" +
	"\videntity_id\x18\x01 \x01(\tR\n" +
	"identityId\x12+\n" +
	"\x11organization_name\x18\x02 \x01(\tR\x10organizationName\"\xc1\x01\n" +
	"\vUserSummary\x12\x1f\n" +
	"\videntity_id\x18\x01 \x01(\tR\n" +
	"identityId\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\x12\x1d\n" +
	"\n" +
	"first_name\x18\x03 \x01(\tR\tfirstName\x12\x1b\n" +
	"\tlast_name\x18\x04 \x01(\tR\blastName\x12+\n" +
	"\x11organization_name\x18\x05 \x01(\tR\x10organizationName\x12\x12\n" +
	"\x04role\x18\x06 \x01(\tR\x04role2\xf2\x06\n" +
	"\x0eTenantsService\x12\x8f\x01\n" +
	"\x12RegisterMasterUser\x12%.tenants.v1.RegisterMasterUserRequest\x1a&.tenants.v1.RegisterMasterUserResponse\"*\x82\xd3\xe4\x93\x02$:\x01*\"\x1f/api/v1/um/register_master_user\x12e\n" +
	"\tLoginUser\x12\x1c.tenants.v1.LoginUserRequest\x1a\x1d.tenants.v1.LoginUserResponse\"\x1b\x82\xd3\xe4\x93\x02\x15:\x01*\"\x10/api/v1/um/login\x12h\n" +
	"\vGetJWTToken\x12\x1e.tenants.v1.GetJWTTokenRequest\x1a\x1f.tenants.v1.GetJWTTokenResponse\"\x18\x82\xd3\xe4\x93\x02\x12\x12\x10/api/v1/um/token\x12{\n" +
	"\rCreateSubUser\x12 .tenants.v1.CreateSubUserRequest\x1a!.tenants.v1.CreateSubUserResponse\"%\x82\xd3\xe4\x93\x02\x1f:\x01*\"\x1a/api/v1/um/create_sub_user\x12t\n" +
	"\fListSubUsers\x12\x1f.tenants.v1.ListSubUsersRequest\x1a .tenants.v1.ListSubUsersResponse\"!\x82\xd3\xe4\x93\x02\x1b\x12\x19/api/v1/um/list_all_users\x12\x80\x01\n" +
	"\rDeleteSubUser\x12\x1d.tenants.v1.DeleteUserRequest\x1a\x1e.tenants.v1.DeleteUserResponse\"0\x82\xd3\xe4\x93\x02**(/api/v1/um/delete_sub_user/{identity_id}\x12\x86\x01\n" +
	"\x10DeleteMasterUser\x12\x1d.tenants.v1.DeleteUserRequest\x1a\x1e.tenants.v1.DeleteUserResponse\"3\x82\xd3\xe4\x93\x02-*+/api/v1/um/delete_master_user/{identity_id}B#Z!user-management/api/tenants/v1;v1b\x06proto3"

var (
	file_tenants_v1_tenants_proto_rawDescOnce sync.Once
	file_tenants_v1_tenants_proto_rawDescData []byte
)

func file_tenants_v1_tenants_proto_rawDescGZIP() []byte {
	file_tenants_v1_tenants_proto_rawDescOnce.Do(func() {
		file_tenants_v1_tenants_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_tenants_v1_tenants_proto_rawDesc), len(file_tenants_v1_tenants_proto_rawDesc)))
	})
	return file_tenants_v1_tenants_proto_rawDescData
}

var file_tenants_v1_tenants_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_tenants_v1_tenants_proto_goTypes = []any{
	(*RegisterMasterUserRequest)(nil),  // 0: tenants.v1.RegisterMasterUserRequest
	(*RegisterMasterUserResponse)(nil), // 1: tenants.v1.RegisterMasterUserResponse
	(*LoginUserRequest)(nil),           // 2: tenants.v1.LoginUserRequest
	(*LoginUserResponse)(nil),          // 3: tenants.v1.LoginUserResponse
	(*UserInfo)(nil),                   // 4: tenants.v1.UserInfo
	(*GetJWTTokenRequest)(nil),         // 5: tenants.v1.GetJWTTokenRequest
	(*GetJWTTokenResponse)(nil),        // 6: tenants.v1.GetJWTTokenResponse
	(*CreateSubUserRequest)(nil),       // 7: tenants.v1.CreateSubUserRequest
	(*CreateSubUserResponse)(nil),      // 8: tenants.v1.CreateSubUserResponse
	(*ListSubUsersRequest)(nil),        // 9: tenants.v1.ListSubUsersRequest
	(*ListSubUsersResponse)(nil),       // 10: tenants.v1.ListSubUsersResponse
	(*DeleteUserRequest)(nil),          // 11: tenants.v1.DeleteUserRequest
	(*DeleteUserResponse)(nil),         // 12: tenants.v1.DeleteUserResponse
	(*TenantData)(nil),                 // 13: tenants.v1.TenantData
	(*TokenData)(nil),                  // 14: tenants.v1.TokenData
	(*UserData)(nil),                   // 15: tenants.v1.UserData
	(*UserSummary)(nil),                // 16: tenants.v1.UserSummary
}
var file_tenants_v1_tenants_proto_depIdxs = []int32{
	13, // 0: tenants.v1.RegisterMasterUserResponse.data:type_name -> tenants.v1.TenantData
	4,  // 1: tenants.v1.LoginUserResponse.user:type_name -> tenants.v1.UserInfo
	14, // 2: tenants.v1.GetJWTTokenResponse.data:type_name -> tenants.v1.TokenData
	15, // 3: tenants.v1.CreateSubUserResponse.data:type_name -> tenants.v1.UserData
	16, // 4: tenants.v1.ListSubUsersResponse.users:type_name -> tenants.v1.UserSummary
	0,  // 5: tenants.v1.TenantsService.RegisterMasterUser:input_type -> tenants.v1.RegisterMasterUserRequest
	2,  // 6: tenants.v1.TenantsService.LoginUser:input_type -> tenants.v1.LoginUserRequest
	5,  // 7: tenants.v1.TenantsService.GetJWTToken:input_type -> tenants.v1.GetJWTTokenRequest
	7,  // 8: tenants.v1.TenantsService.CreateSubUser:input_type -> tenants.v1.CreateSubUserRequest
	9,  // 9: tenants.v1.TenantsService.ListSubUsers:input_type -> tenants.v1.ListSubUsersRequest
	11, // 10: tenants.v1.TenantsService.DeleteSubUser:input_type -> tenants.v1.DeleteUserRequest
	11, // 11: tenants.v1.TenantsService.DeleteMasterUser:input_type -> tenants.v1.DeleteUserRequest
	1,  // 12: tenants.v1.TenantsService.RegisterMasterUser:output_type -> tenants.v1.RegisterMasterUserResponse
	3,  // 13: tenants.v1.TenantsService.LoginUser:output_type -> tenants.v1.LoginUserResponse
	6,  // 14: tenants.v1.TenantsService.GetJWTToken:output_type -> tenants.v1.GetJWTTokenResponse
	8,  // 15: tenants.v1.TenantsService.CreateSubUser:output_type -> tenants.v1.CreateSubUserResponse
	10, // 16: tenants.v1.TenantsService.ListSubUsers:output_type -> tenants.v1.ListSubUsersResponse
	12, // 17: tenants.v1.TenantsService.DeleteSubUser:output_type -> tenants.v1.DeleteUserResponse
	12, // 18: tenants.v1.TenantsService.DeleteMasterUser:output_type -> tenants.v1.DeleteUserResponse
	12, // [12:19] is the sub-list for method output_type
	5,  // [5:12] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_tenants_v1_tenants_proto_init() }
func file_tenants_v1_tenants_proto_init() {
	if File_tenants_v1_tenants_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_tenants_v1_tenants_proto_rawDesc), len(file_tenants_v1_tenants_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   17,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_tenants_v1_tenants_proto_goTypes,
		DependencyIndexes: file_tenants_v1_tenants_proto_depIdxs,
		MessageInfos:      file_tenants_v1_tenants_proto_msgTypes,
	}.Build()
	File_tenants_v1_tenants_proto = out.File
	file_tenants_v1_tenants_proto_goTypes = nil
	file_tenants_v1_tenants_proto_depIdxs = nil
}
