// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v4.25.1
// source: tenants/v1/tenants.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	TenantsService_RegisterMasterUser_FullMethodName = "/tenants.v1.TenantsService/RegisterMasterUser"
	TenantsService_LoginUser_FullMethodName          = "/tenants.v1.TenantsService/LoginUser"
	TenantsService_GetJWTToken_FullMethodName        = "/tenants.v1.TenantsService/GetJWTToken"
	TenantsService_CreateSubUser_FullMethodName      = "/tenants.v1.TenantsService/CreateSubUser"
	TenantsService_ListSubUsers_FullMethodName       = "/tenants.v1.TenantsService/ListSubUsers"
	TenantsService_DeleteSubUser_FullMethodName      = "/tenants.v1.TenantsService/DeleteSubUser"
	TenantsService_DeleteMasterUser_FullMethodName   = "/tenants.v1.TenantsService/DeleteMasterUser"
)

// TenantsServiceClient is the client API for TenantsService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TenantsServiceClient interface {
	RegisterMasterUser(ctx context.Context, in *RegisterMasterUserRequest, opts ...grpc.CallOption) (*RegisterMasterUserResponse, error)
	// NEW: Login endpoint
	LoginUser(ctx context.Context, in *LoginUserRequest, opts ...grpc.CallOption) (*LoginUserResponse, error)
	GetJWTToken(ctx context.Context, in *GetJWTTokenRequest, opts ...grpc.CallOption) (*GetJWTTokenResponse, error)
	CreateSubUser(ctx context.Context, in *CreateSubUserRequest, opts ...grpc.CallOption) (*CreateSubUserResponse, error)
	ListSubUsers(ctx context.Context, in *ListSubUsersRequest, opts ...grpc.CallOption) (*ListSubUsersResponse, error)
	DeleteSubUser(ctx context.Context, in *DeleteUserRequest, opts ...grpc.CallOption) (*DeleteUserResponse, error)
	DeleteMasterUser(ctx context.Context, in *DeleteUserRequest, opts ...grpc.CallOption) (*DeleteUserResponse, error)
}

type tenantsServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTenantsServiceClient(cc grpc.ClientConnInterface) TenantsServiceClient {
	return &tenantsServiceClient{cc}
}

func (c *tenantsServiceClient) RegisterMasterUser(ctx context.Context, in *RegisterMasterUserRequest, opts ...grpc.CallOption) (*RegisterMasterUserResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RegisterMasterUserResponse)
	err := c.cc.Invoke(ctx, TenantsService_RegisterMasterUser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tenantsServiceClient) LoginUser(ctx context.Context, in *LoginUserRequest, opts ...grpc.CallOption) (*LoginUserResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LoginUserResponse)
	err := c.cc.Invoke(ctx, TenantsService_LoginUser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tenantsServiceClient) GetJWTToken(ctx context.Context, in *GetJWTTokenRequest, opts ...grpc.CallOption) (*GetJWTTokenResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetJWTTokenResponse)
	err := c.cc.Invoke(ctx, TenantsService_GetJWTToken_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tenantsServiceClient) CreateSubUser(ctx context.Context, in *CreateSubUserRequest, opts ...grpc.CallOption) (*CreateSubUserResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateSubUserResponse)
	err := c.cc.Invoke(ctx, TenantsService_CreateSubUser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tenantsServiceClient) ListSubUsers(ctx context.Context, in *ListSubUsersRequest, opts ...grpc.CallOption) (*ListSubUsersResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListSubUsersResponse)
	err := c.cc.Invoke(ctx, TenantsService_ListSubUsers_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tenantsServiceClient) DeleteSubUser(ctx context.Context, in *DeleteUserRequest, opts ...grpc.CallOption) (*DeleteUserResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteUserResponse)
	err := c.cc.Invoke(ctx, TenantsService_DeleteSubUser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tenantsServiceClient) DeleteMasterUser(ctx context.Context, in *DeleteUserRequest, opts ...grpc.CallOption) (*DeleteUserResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteUserResponse)
	err := c.cc.Invoke(ctx, TenantsService_DeleteMasterUser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TenantsServiceServer is the server API for TenantsService service.
// All implementations must embed UnimplementedTenantsServiceServer
// for forward compatibility.
type TenantsServiceServer interface {
	RegisterMasterUser(context.Context, *RegisterMasterUserRequest) (*RegisterMasterUserResponse, error)
	// NEW: Login endpoint
	LoginUser(context.Context, *LoginUserRequest) (*LoginUserResponse, error)
	GetJWTToken(context.Context, *GetJWTTokenRequest) (*GetJWTTokenResponse, error)
	CreateSubUser(context.Context, *CreateSubUserRequest) (*CreateSubUserResponse, error)
	ListSubUsers(context.Context, *ListSubUsersRequest) (*ListSubUsersResponse, error)
	DeleteSubUser(context.Context, *DeleteUserRequest) (*DeleteUserResponse, error)
	DeleteMasterUser(context.Context, *DeleteUserRequest) (*DeleteUserResponse, error)
	mustEmbedUnimplementedTenantsServiceServer()
}

// UnimplementedTenantsServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTenantsServiceServer struct{}

func (UnimplementedTenantsServiceServer) RegisterMasterUser(context.Context, *RegisterMasterUserRequest) (*RegisterMasterUserResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RegisterMasterUser not implemented")
}
func (UnimplementedTenantsServiceServer) LoginUser(context.Context, *LoginUserRequest) (*LoginUserResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method LoginUser not implemented")
}
func (UnimplementedTenantsServiceServer) GetJWTToken(context.Context, *GetJWTTokenRequest) (*GetJWTTokenResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetJWTToken not implemented")
}
func (UnimplementedTenantsServiceServer) CreateSubUser(context.Context, *CreateSubUserRequest) (*CreateSubUserResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateSubUser not implemented")
}
func (UnimplementedTenantsServiceServer) ListSubUsers(context.Context, *ListSubUsersRequest) (*ListSubUsersResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListSubUsers not implemented")
}
func (UnimplementedTenantsServiceServer) DeleteSubUser(context.Context, *DeleteUserRequest) (*DeleteUserResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteSubUser not implemented")
}
func (UnimplementedTenantsServiceServer) DeleteMasterUser(context.Context, *DeleteUserRequest) (*DeleteUserResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteMasterUser not implemented")
}
func (UnimplementedTenantsServiceServer) mustEmbedUnimplementedTenantsServiceServer() {}
func (UnimplementedTenantsServiceServer) testEmbeddedByValue()                        {}

// UnsafeTenantsServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TenantsServiceServer will
// result in compilation errors.
type UnsafeTenantsServiceServer interface {
	mustEmbedUnimplementedTenantsServiceServer()
}

func RegisterTenantsServiceServer(s grpc.ServiceRegistrar, srv TenantsServiceServer) {
	// If the following call panics, it indicates UnimplementedTenantsServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&TenantsService_ServiceDesc, srv)
}

func _TenantsService_RegisterMasterUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterMasterUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TenantsServiceServer).RegisterMasterUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TenantsService_RegisterMasterUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TenantsServiceServer).RegisterMasterUser(ctx, req.(*RegisterMasterUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TenantsService_LoginUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoginUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TenantsServiceServer).LoginUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TenantsService_LoginUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TenantsServiceServer).LoginUser(ctx, req.(*LoginUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TenantsService_GetJWTToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetJWTTokenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TenantsServiceServer).GetJWTToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TenantsService_GetJWTToken_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TenantsServiceServer).GetJWTToken(ctx, req.(*GetJWTTokenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TenantsService_CreateSubUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateSubUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TenantsServiceServer).CreateSubUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TenantsService_CreateSubUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TenantsServiceServer).CreateSubUser(ctx, req.(*CreateSubUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TenantsService_ListSubUsers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListSubUsersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TenantsServiceServer).ListSubUsers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TenantsService_ListSubUsers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TenantsServiceServer).ListSubUsers(ctx, req.(*ListSubUsersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TenantsService_DeleteSubUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TenantsServiceServer).DeleteSubUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TenantsService_DeleteSubUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TenantsServiceServer).DeleteSubUser(ctx, req.(*DeleteUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TenantsService_DeleteMasterUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TenantsServiceServer).DeleteMasterUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TenantsService_DeleteMasterUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TenantsServiceServer).DeleteMasterUser(ctx, req.(*DeleteUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// TenantsService_ServiceDesc is the grpc.ServiceDesc for TenantsService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TenantsService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "tenants.v1.TenantsService",
	HandlerType: (*TenantsServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RegisterMasterUser",
			Handler:    _TenantsService_RegisterMasterUser_Handler,
		},
		{
			MethodName: "LoginUser",
			Handler:    _TenantsService_LoginUser_Handler,
		},
		{
			MethodName: "GetJWTToken",
			Handler:    _TenantsService_GetJWTToken_Handler,
		},
		{
			MethodName: "CreateSubUser",
			Handler:    _TenantsService_CreateSubUser_Handler,
		},
		{
			MethodName: "ListSubUsers",
			Handler:    _TenantsService_ListSubUsers_Handler,
		},
		{
			MethodName: "DeleteSubUser",
			Handler:    _TenantsService_DeleteSubUser_Handler,
		},
		{
			MethodName: "DeleteMasterUser",
			Handler:    _TenantsService_DeleteMasterUser_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "tenants/v1/tenants.proto",
}
